export interface AdapterInfo {
  country: string;
  flag: string;
  plugTypes: string[];
  voltage: string;
  frequency: string;
  euroCompatible: boolean;
  adapterNeeded: string;
  notes: string;
}

export const adaptersByCountry: AdapterInfo[] = [
  {
    country: 'Italia',
    flag: '🇮🇹',
    plugTypes: ['C', 'F', 'L'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno (presa tipo L per 3 poli)',
    notes: 'La presa italiana tipo L ha 3 pin allineati. Le spine europee tipo C funzionano ovunque.',
  },
  {
    country: 'Regno Unito',
    flag: '🇬🇧',
    plugTypes: ['G'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → UK (tipo G)',
    notes: 'Presa a 3 pin rettangolari. Adattatore obbligatorio per dispositivi europei. Facilmente reperibile in aeroporto.',
  },
  {
    country: 'Stati Uniti',
    flag: '🇺🇸',
    plugTypes: ['A', 'B'],
    voltage: '120V',
    frequency: '60Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → US + trasformatore di tensione',
    notes: 'Tensione 120V! Verifica che i tuoi dispositivi supportino 100-240V (la maggior parte dei caricatori sì). Per phon e piastre serve un trasformatore.',
  },
  {
    country: 'Giappone',
    flag: '🇯🇵',
    plugTypes: ['A', 'B'],
    voltage: '100V',
    frequency: '50/60Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → JP + trasformatore',
    notes: 'Tensione molto bassa (100V). La maggior parte dei caricatori moderni (100-240V) funziona. Per altri dispositivi serve trasformatore.',
  },
  {
    country: 'Australia',
    flag: '🇦🇺',
    plugTypes: ['I'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → AU (tipo I)',
    notes: 'Presa a 3 pin inclinati. Tensione compatibile (230V), serve solo l\'adattatore fisico.',
  },
  {
    country: 'Thailandia',
    flag: '🇹🇭',
    plugTypes: ['A', 'B', 'C', 'O'],
    voltage: '220V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Generalmente non necessario',
    notes: 'Le prese tipo C europee funzionano nella maggior parte delle strutture. In hotel di lusso trovi prese universali.',
  },
  {
    country: 'Brasile',
    flag: '🇧🇷',
    plugTypes: ['N'],
    voltage: '127/220V',
    frequency: '60Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → BR (tipo N)',
    notes: 'Attenzione: la tensione varia tra 127V e 220V a seconda della regione. Verifica SEMPRE prima di collegare dispositivi.',
  },
  {
    country: 'India',
    flag: '🇮🇳',
    plugTypes: ['C', 'D', 'M'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Consigliato adattatore universale',
    notes: 'Le spine tipo C europee spesso funzionano, ma le prese indiane tipo D sono più grandi. Un adattatore universale è la scelta migliore.',
  },
  {
    country: 'Cina',
    flag: '🇨🇳',
    plugTypes: ['A', 'C', 'I'],
    voltage: '220V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Generalmente non necessario',
    notes: 'La maggior parte delle prese accetta spine tipo C europee. Gli hotel hanno spesso prese universali.',
  },
  {
    country: 'Sudafrica',
    flag: '🇿🇦',
    plugTypes: ['C', 'D', 'M', 'N'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → ZA (tipo M/N)',
    notes: 'Presa tipo M a 3 pin rotondi grandi. Le spine tipo C possono funzionare in alcune prese, ma un adattatore è consigliato.',
  },
  {
    country: 'Emirati Arabi',
    flag: '🇦🇪',
    plugTypes: ['C', 'G'],
    voltage: '220V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Consigliato per prese tipo G',
    notes: 'Mix di prese europee (tipo C) e britanniche (tipo G). Gli hotel hanno spesso entrambe o prese universali.',
  },
  {
    country: 'Messico',
    flag: '🇲🇽',
    plugTypes: ['A', 'B'],
    voltage: '127V',
    frequency: '60Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → US/MX',
    notes: 'Stesse prese degli USA. Tensione 127V. I caricatori moderni (100-240V) funzionano con solo adattatore.',
  },
  {
    country: 'Francia',
    flag: '🇫🇷',
    plugTypes: ['C', 'E'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese tipo C/E pienamente compatibili con spine europee. Nessun adattatore necessario.',
  },
  {
    country: 'Germania',
    flag: '🇩🇪',
    plugTypes: ['C', 'F'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese Schuko (tipo F) pienamente compatibili con dispositivi europei.',
  },
  {
    country: 'Spagna',
    flag: '🇪🇸',
    plugTypes: ['C', 'F'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese europee standard. Nessun adattatore necessario per viaggiatori europei.',
  },
  {
    country: 'Portogallo',
    flag: '🇵🇹',
    plugTypes: ['C', 'F'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese europee standard. Nessun adattatore necessario.',
  },
  {
    country: 'Grecia',
    flag: '🇬🇷',
    plugTypes: ['C', 'F'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese europee standard tipo C/F.',
  },
  {
    country: 'Paesi Bassi',
    flag: '🇳🇱',
    plugTypes: ['C', 'F'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese Schuko standard europee.',
  },
  {
    country: 'Belgio',
    flag: '🇧🇪',
    plugTypes: ['C', 'E'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese tipo C/E come in Francia.',
  },
  {
    country: 'Austria',
    flag: '🇦🇹',
    plugTypes: ['C', 'F'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese Schuko standard europee.',
  },
  {
    country: 'Svizzera',
    flag: '🇨🇭',
    plugTypes: ['C', 'J'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Per spine a 3 poli serve adattatore tipo J',
    notes: 'Le spine tipo C a 2 poli funzionano. Per spine a 3 poli serve adattatore svizzero tipo J.',
  },
  {
    country: 'Svezia',
    flag: '🇸🇪',
    plugTypes: ['C', 'F'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese Schuko standard europee.',
  },
  {
    country: 'Norvegia',
    flag: '🇳🇴',
    plugTypes: ['C', 'F'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese Schuko standard europee.',
  },
  {
    country: 'Danimarca',
    flag: '🇩🇰',
    plugTypes: ['C', 'E', 'F', 'K'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Le spine europee tipo C funzionano. La presa danese tipo K è compatibile.',
  },
  {
    country: 'Finlandia',
    flag: '🇫🇮',
    plugTypes: ['C', 'F'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese Schuko standard europee.',
  },
  {
    country: 'Irlanda',
    flag: '🇮🇪',
    plugTypes: ['G'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → UK/IE (tipo G)',
    notes: 'Stesse prese del Regno Unito. Adattatore obbligatorio.',
  },
  {
    country: 'Polonia',
    flag: '🇵🇱',
    plugTypes: ['C', 'E'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese europee tipo C/E.',
  },
  {
    country: 'Repubblica Ceca',
    flag: '🇨🇿',
    plugTypes: ['C', 'E'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese europee tipo C/E.',
  },
  {
    country: 'Ungheria',
    flag: '🇭🇺',
    plugTypes: ['C', 'F'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese Schuko standard europee.',
  },
  {
    country: 'Romania',
    flag: '🇷🇴',
    plugTypes: ['C', 'F'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese Schuko standard europee.',
  },
  {
    country: 'Bulgaria',
    flag: '🇧🇬',
    plugTypes: ['C', 'F'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese Schuko standard europee.',
  },
  {
    country: 'Croazia',
    flag: '🇭🇷',
    plugTypes: ['C', 'F'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese europee standard.',
  },
  {
    country: 'Slovenia',
    flag: '🇸🇮',
    plugTypes: ['C', 'F'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese europee standard.',
  },
  {
    country: 'Serbia',
    flag: '🇷🇸',
    plugTypes: ['C', 'F'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese Schuko standard europee.',
  },
  {
    country: 'Turchia',
    flag: '🇹🇷',
    plugTypes: ['C', 'F'],
    voltage: '220V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese europee standard. Tensione 220V compatibile.',
  },
  {
    country: 'Russia',
    flag: '🇷🇺',
    plugTypes: ['C', 'F'],
    voltage: '220V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese europee tipo C/F. Tensione 220V compatibile.',
  },
  {
    country: 'Islanda',
    flag: '🇮🇸',
    plugTypes: ['C', 'F'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese Schuko standard europee.',
  },
  {
    country: 'Canada',
    flag: '🇨🇦',
    plugTypes: ['A', 'B'],
    voltage: '120V',
    frequency: '60Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → US/CA',
    notes: 'Stesse prese degli USA. Tensione 120V, i caricatori moderni funzionano.',
  },
  {
    country: 'Argentina',
    flag: '🇦🇷',
    plugTypes: ['C', 'I'],
    voltage: '220V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Consigliato adattatore per tipo I',
    notes: 'Le spine tipo C europee funzionano in molte prese. Per prese tipo I serve adattatore.',
  },
  {
    country: 'Cile',
    flag: '🇨🇱',
    plugTypes: ['C', 'L'],
    voltage: '220V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Generalmente non necessario',
    notes: 'Le spine tipo C europee funzionano nella maggior parte delle prese.',
  },
  {
    country: 'Colombia',
    flag: '🇨🇴',
    plugTypes: ['A', 'B'],
    voltage: '110V',
    frequency: '60Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → US/CO',
    notes: 'Stesse prese degli USA. Tensione 110V. Verifica compatibilità dispositivi.',
  },
  {
    country: 'Perù',
    flag: '🇵🇪',
    plugTypes: ['A', 'B', 'C'],
    voltage: '220V',
    frequency: '60Hz',
    euroCompatible: true,
    adapterNeeded: 'Consigliato adattatore universale',
    notes: 'Mix di prese. Le spine tipo C funzionano in alcune prese. Adattatore universale consigliato.',
  },
  {
    country: 'Cuba',
    flag: '🇨🇺',
    plugTypes: ['A', 'B'],
    voltage: '110/220V',
    frequency: '60Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → US',
    notes: 'La tensione può variare. Hotel moderni spesso hanno 220V. Porta adattatore universale.',
  },
  {
    country: 'Costa Rica',
    flag: '🇨🇷',
    plugTypes: ['A', 'B'],
    voltage: '120V',
    frequency: '60Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → US/CR',
    notes: 'Stesse prese degli USA.',
  },
  {
    country: 'Corea del Sud',
    flag: '🇰🇷',
    plugTypes: ['C', 'F'],
    voltage: '220V',
    frequency: '60Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese europee tipo C/F. Nessun adattatore necessario.',
  },
  {
    country: 'Vietnam',
    flag: '🇻🇳',
    plugTypes: ['A', 'B', 'C'],
    voltage: '220V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Generalmente non necessario',
    notes: 'La maggior parte delle prese accetta spine europee tipo C.',
  },
  {
    country: 'Indonesia',
    flag: '🇮🇩',
    plugTypes: ['C', 'F'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese europee tipo C/F. Nessun adattatore necessario.',
  },
  {
    country: 'Malesia',
    flag: '🇲🇾',
    plugTypes: ['G'],
    voltage: '240V',
    frequency: '50Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → MY (tipo G)',
    notes: 'Stesse prese del Regno Unito. Adattatore obbligatorio.',
  },
  {
    country: 'Singapore',
    flag: '🇸🇬',
    plugTypes: ['G'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → SG (tipo G)',
    notes: 'Stesse prese del Regno Unito. Gli hotel spesso forniscono adattatori.',
  },
  {
    country: 'Filippine',
    flag: '🇵🇭',
    plugTypes: ['A', 'B', 'C'],
    voltage: '220V',
    frequency: '60Hz',
    euroCompatible: true,
    adapterNeeded: 'Consigliato adattatore universale',
    notes: 'Mix di prese americane ed europee. Adattatore universale consigliato.',
  },
  {
    country: 'Taiwan',
    flag: '🇹🇼',
    plugTypes: ['A', 'B'],
    voltage: '110V',
    frequency: '60Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → US/TW',
    notes: 'Stesse prese degli USA/Giappone. Tensione 110V.',
  },
  {
    country: 'Egitto',
    flag: '🇪🇬',
    plugTypes: ['C', 'F'],
    voltage: '220V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese europee tipo C. Nessun adattatore necessario.',
  },
  {
    country: 'Marocco',
    flag: '🇲🇦',
    plugTypes: ['C', 'E'],
    voltage: '220V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese francesi tipo C/E. Compatibili con spine europee.',
  },
  {
    country: 'Tunisia',
    flag: '🇹🇳',
    plugTypes: ['C', 'E'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese francesi tipo C/E. Compatibili con spine europee.',
  },
  {
    country: 'Kenya',
    flag: '🇰🇪',
    plugTypes: ['G'],
    voltage: '240V',
    frequency: '50Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → KE (tipo G)',
    notes: 'Stesse prese del Regno Unito. Adattatore obbligatorio.',
  },
  {
    country: 'Tanzania',
    flag: '🇹🇿',
    plugTypes: ['D', 'G'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → TZ (tipo G/D)',
    notes: 'Prese britanniche e indiane. Adattatore necessario.',
  },
  {
    country: 'Nigeria',
    flag: '🇳🇬',
    plugTypes: ['D', 'G'],
    voltage: '240V',
    frequency: '50Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → NG (tipo G)',
    notes: 'Prese britanniche. Adattatore obbligatorio. Tensione instabile, consigliato stabilizzatore.',
  },
  {
    country: 'Arabia Saudita',
    flag: '🇸🇦',
    plugTypes: ['A', 'B', 'G'],
    voltage: '220V',
    frequency: '60Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore universale consigliato',
    notes: 'Mix di prese americane e britanniche. Porta adattatore universale.',
  },
  {
    country: 'Qatar',
    flag: '🇶🇦',
    plugTypes: ['G'],
    voltage: '240V',
    frequency: '50Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → QA (tipo G)',
    notes: 'Prese britanniche. Gli hotel di lusso hanno spesso prese universali.',
  },
  {
    country: 'Israele',
    flag: '🇮🇱',
    plugTypes: ['C', 'H'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Generalmente non necessario',
    notes: 'Le spine tipo C europee funzionano. La presa israeliana tipo H accetta anche tipo C.',
  },
  {
    country: 'Giordania',
    flag: '🇯🇴',
    plugTypes: ['B', 'C', 'D', 'F', 'G', 'J'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Consigliato adattatore universale',
    notes: 'Mix di molti tipi di prese. Adattatore universale molto consigliato.',
  },
  {
    country: 'Nuova Zelanda',
    flag: '🇳🇿',
    plugTypes: ['I'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → NZ (tipo I)',
    notes: 'Stesse prese dell\'Australia. Tensione compatibile, serve solo adattatore fisico.',
  },
  {
    country: 'Ucraina',
    flag: '🇺🇦',
    plugTypes: ['C', 'F'],
    voltage: '220V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese europee tipo C/F.',
  },
  {
    country: 'Georgia',
    flag: '🇬🇪',
    plugTypes: ['C', 'F'],
    voltage: '220V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese europee tipo C/F.',
  },
  {
    country: 'Nepal',
    flag: '🇳🇵',
    plugTypes: ['C', 'D', 'M'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Consigliato adattatore universale',
    notes: 'Le spine tipo C funzionano in molte prese. Corrente instabile, porta protezione per dispositivi.',
  },
  {
    country: 'Sri Lanka',
    flag: '🇱🇰',
    plugTypes: ['D', 'G', 'M'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → LK (tipo D/G)',
    notes: 'Mix di prese britanniche e indiane. Adattatore necessario.',
  },
  {
    country: 'Cambogia',
    flag: '🇰🇭',
    plugTypes: ['A', 'C', 'G'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Generalmente non necessario',
    notes: 'Mix di prese. Le spine tipo C europee funzionano nella maggior parte dei casi.',
  },
  {
    country: 'Myanmar',
    flag: '🇲🇲',
    plugTypes: ['C', 'D', 'F', 'G'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Consigliato adattatore universale',
    notes: 'Mix di tipi di prese. Corrente instabile in zone rurali.',
  },
  {
    country: 'Mongolia',
    flag: '🇲🇳',
    plugTypes: ['C', 'E'],
    voltage: '220V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese europee tipo C/E.',
  },
  {
    country: 'Etiopia',
    flag: '🇪🇹',
    plugTypes: ['C', 'E', 'F', 'L'],
    voltage: '220V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Generalmente non necessario',
    notes: 'Prese europee. Corrente instabile, porta power bank e protezione.',
  },
  {
    country: 'Ghana',
    flag: '🇬🇭',
    plugTypes: ['D', 'G'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → GH (tipo G)',
    notes: 'Prese britanniche. Adattatore necessario.',
  },
  {
    country: 'Senegal',
    flag: '🇸🇳',
    plugTypes: ['C', 'D', 'E', 'K'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Generalmente non necessario',
    notes: 'Prese francesi tipo C/E. Compatibili con spine europee.',
  },
  {
    country: 'Madagascar',
    flag: '🇲🇬',
    plugTypes: ['C', 'D', 'E', 'J', 'K'],
    voltage: '220V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Generalmente non necessario',
    notes: 'Prese francesi tipo C/E. Corrente instabile in zone rurali.',
  },
  {
    country: 'Albania',
    flag: '🇦🇱',
    plugTypes: ['C', 'F'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese europee standard.',
  },
  {
    country: 'Malta',
    flag: '🇲🇹',
    plugTypes: ['G'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → MT (tipo G)',
    notes: 'Prese britanniche. Adattatore obbligatorio.',
  },
  {
    country: 'Cipro',
    flag: '🇨🇾',
    plugTypes: ['G'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → CY (tipo G)',
    notes: 'Prese britanniche. Adattatore obbligatorio.',
  },
  {
    country: 'Pakistan',
    flag: '🇵🇰',
    plugTypes: ['C', 'D'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Consigliato adattatore universale',
    notes: 'Le spine tipo C funzionano in molte prese. Corrente molto instabile.',
  },
  {
    country: 'Bangladesh',
    flag: '🇧🇩',
    plugTypes: ['A', 'C', 'D', 'G', 'K'],
    voltage: '220V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Consigliato adattatore universale',
    notes: 'Mix di prese diverse. Adattatore universale molto consigliato.',
  },
  {
    country: 'Iran',
    flag: '🇮🇷',
    plugTypes: ['C', 'F'],
    voltage: '220V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese europee tipo C/F.',
  },
];

export const plugTypeDescriptions: Record<string, { name: string; description: string }> = {
  'A': { name: 'Tipo A', description: '2 pin piatti paralleli' },
  'B': { name: 'Tipo B', description: '2 pin piatti + terra rotondo' },
  'C': { name: 'Tipo C', description: '2 pin rotondi (Europlug)' },
  'D': { name: 'Tipo D', description: '3 pin rotondi grandi triangolari' },
  'E': { name: 'Tipo E', description: '2 pin rotondi + foro terra' },
  'F': { name: 'Tipo F', description: '2 pin rotondi + clip terra (Schuko)' },
  'G': { name: 'Tipo G', description: '3 pin rettangolari (UK)' },
  'H': { name: 'Tipo H', description: '3 pin (Israele)' },
  'I': { name: 'Tipo I', description: '2 pin inclinati + terra (AU)' },
  'J': { name: 'Tipo J', description: '3 pin rotondi (CH)' },
  'K': { name: 'Tipo K', description: '3 pin rotondi (DK)' },
  'L': { name: 'Tipo L', description: '3 pin rotondi allineati (IT)' },
  'M': { name: 'Tipo M', description: '3 pin rotondi grandi' },
  'N': { name: 'Tipo N', description: '3 pin rotondi (BR)' },
  'O': { name: 'Tipo O', description: '2 pin rotondi + terra rotondo' },
};
