export interface AdapterInfo {
  country: string;
  flag: string;
  plugTypes: string[];
  voltage: string;
  frequency: string;
  euroCompatible: boolean;
  adapterNeeded: string;
  notes: string;
}

export const adaptersByCountry: AdapterInfo[] = [
  {
    country: 'Italia',
    flag: '🇮🇹',
    plugTypes: ['C', 'F', 'L'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno (presa tipo L per 3 poli)',
    notes: 'La presa italiana tipo L ha 3 pin allineati. Le spine europee tipo C funzionano ovunque.',
  },
  {
    country: 'Regno Unito',
    flag: '🇬🇧',
    plugTypes: ['G'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → UK (tipo G)',
    notes: 'Presa a 3 pin rettangolari. Adattatore obbligatorio per dispositivi europei. Facilmente reperibile in aeroporto.',
  },
  {
    country: 'Stati Uniti',
    flag: '🇺🇸',
    plugTypes: ['A', 'B'],
    voltage: '120V',
    frequency: '60Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → US + trasformatore di tensione',
    notes: 'Tensione 120V! Verifica che i tuoi dispositivi supportino 100-240V (la maggior parte dei caricatori sì). Per phon e piastre serve un trasformatore.',
  },
  {
    country: 'Giappone',
    flag: '🇯🇵',
    plugTypes: ['A', 'B'],
    voltage: '100V',
    frequency: '50/60Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → JP + trasformatore',
    notes: 'Tensione molto bassa (100V). La maggior parte dei caricatori moderni (100-240V) funziona. Per altri dispositivi serve trasformatore.',
  },
  {
    country: 'Australia',
    flag: '🇦🇺',
    plugTypes: ['I'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → AU (tipo I)',
    notes: 'Presa a 3 pin inclinati. Tensione compatibile (230V), serve solo l\'adattatore fisico.',
  },
  {
    country: 'Thailandia',
    flag: '🇹🇭',
    plugTypes: ['A', 'B', 'C', 'O'],
    voltage: '220V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Generalmente non necessario',
    notes: 'Le prese tipo C europee funzionano nella maggior parte delle strutture. In hotel di lusso trovi prese universali.',
  },
  {
    country: 'Brasile',
    flag: '🇧🇷',
    plugTypes: ['N'],
    voltage: '127/220V',
    frequency: '60Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → BR (tipo N)',
    notes: 'Attenzione: la tensione varia tra 127V e 220V a seconda della regione. Verifica SEMPRE prima di collegare dispositivi.',
  },
  {
    country: 'India',
    flag: '🇮🇳',
    plugTypes: ['C', 'D', 'M'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Consigliato adattatore universale',
    notes: 'Le spine tipo C europee spesso funzionano, ma le prese indiane tipo D sono più grandi. Un adattatore universale è la scelta migliore.',
  },
  {
    country: 'Cina',
    flag: '🇨🇳',
    plugTypes: ['A', 'C', 'I'],
    voltage: '220V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Generalmente non necessario',
    notes: 'La maggior parte delle prese accetta spine tipo C europee. Gli hotel hanno spesso prese universali.',
  },
  {
    country: 'Sudafrica',
    flag: '🇿🇦',
    plugTypes: ['C', 'D', 'M', 'N'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → ZA (tipo M/N)',
    notes: 'Presa tipo M a 3 pin rotondi grandi. Le spine tipo C possono funzionare in alcune prese, ma un adattatore è consigliato.',
  },
  {
    country: 'Emirati Arabi',
    flag: '🇦🇪',
    plugTypes: ['C', 'G'],
    voltage: '220V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Consigliato per prese tipo G',
    notes: 'Mix di prese europee (tipo C) e britanniche (tipo G). Gli hotel hanno spesso entrambe o prese universali.',
  },
  {
    country: 'Messico',
    flag: '🇲🇽',
    plugTypes: ['A', 'B'],
    voltage: '127V',
    frequency: '60Hz',
    euroCompatible: false,
    adapterNeeded: 'Adattatore EU → US/MX',
    notes: 'Stesse prese degli USA. Tensione 127V. I caricatori moderni (100-240V) funzionano con solo adattatore.',
  },
  {
    country: 'Francia',
    flag: '🇫🇷',
    plugTypes: ['C', 'E'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese tipo C/E pienamente compatibili con spine europee. Nessun adattatore necessario.',
  },
  {
    country: 'Germania',
    flag: '🇩🇪',
    plugTypes: ['C', 'F'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese Schuko (tipo F) pienamente compatibili con dispositivi europei.',
  },
  {
    country: 'Spagna',
    flag: '🇪🇸',
    plugTypes: ['C', 'F'],
    voltage: '230V',
    frequency: '50Hz',
    euroCompatible: true,
    adapterNeeded: 'Nessuno',
    notes: 'Prese europee standard. Nessun adattatore necessario per viaggiatori europei.',
  },
];

export const plugTypeDescriptions: Record<string, { name: string; description: string }> = {
  'A': { name: 'Tipo A', description: '2 pin piatti paralleli' },
  'B': { name: 'Tipo B', description: '2 pin piatti + terra rotondo' },
  'C': { name: 'Tipo C', description: '2 pin rotondi (Europlug)' },
  'D': { name: 'Tipo D', description: '3 pin rotondi grandi triangolari' },
  'E': { name: 'Tipo E', description: '2 pin rotondi + foro terra' },
  'F': { name: 'Tipo F', description: '2 pin rotondi + clip terra (Schuko)' },
  'G': { name: 'Tipo G', description: '3 pin rettangolari (UK)' },
  'I': { name: 'Tipo I', description: '2 pin inclinati + terra (AU)' },
  'L': { name: 'Tipo L', description: '3 pin rotondi allineati (IT)' },
  'M': { name: 'Tipo M', description: '3 pin rotondi grandi' },
  'N': { name: 'Tipo N', description: '3 pin rotondi (BR)' },
  'O': { name: 'Tipo O', description: '2 pin rotondi + terra rotondo' },
};
