import { ChecklistItem } from '@/types';

export const defaultChecklist: ChecklistItem[] = [
  { id: 'c1', name: 'Passaporto', category: 'Essenziali', checked: false },
  { id: 'c2', name: 'Carta d\'identità', category: 'Essenziali', checked: false },
  { id: 'c3', name: 'Biglietti aerei', category: 'Essenziali', checked: false },
  { id: 'c4', name: 'Assicurazione viaggio', category: 'Essenziali', checked: false },
  { id: 'c5', name: 'Carte di credito', category: 'Essenziali', checked: false },
  { id: 'c6', name: 'Contanti', category: 'Essenziali', checked: false },
  { id: 'c7', name: 'Medicinali', category: 'Essenziali', checked: false },
  { id: 'c8', name: 'Prenotazioni hotel', category: 'Essenziali', checked: false },
  { id: 'c9', name: 'Patente', category: 'Essenziali', checked: false },
  { id: 'c10', name: 'Fotocopie documenti', category: 'Essenziali', checked: false },
  { id: 'c11', name: 'Magliette x5', category: 'Vestiti', checked: false },
  { id: 'c12', name: 'Pantaloni x3', category: 'Vestiti', checked: false },
  { id: 'c13', name: 'Giacca', category: 'Vestiti', checked: false },
  { id: 'c14', name: 'Scarpe comode', category: 'Vestiti', checked: false },
  { id: 'c15', name: 'Costume da bagno', category: 'Vestiti', checked: false },
  { id: 'c16', name: 'Biancheria intima', category: 'Vestiti', checked: false },
  { id: 'c17', name: 'Calzini x5', category: 'Vestiti', checked: false },
  { id: 'c18', name: 'Pigiama', category: 'Vestiti', checked: false },
  { id: 'c19', name: 'Felpa', category: 'Vestiti', checked: false },
  { id: 'c20', name: 'Cappello', category: 'Vestiti', checked: false },
  { id: 'c21', name: 'Occhiali da sole', category: 'Vestiti', checked: false },
  { id: 'c22', name: 'Telefono', category: 'Elettronica', checked: false },
  { id: 'c23', name: 'Caricatore', category: 'Elettronica', checked: false },
  { id: 'c24', name: 'Power bank', category: 'Elettronica', checked: false },
  { id: 'c25', name: 'Cuffie', category: 'Elettronica', checked: false },
  { id: 'c26', name: 'Adattatore presa', category: 'Elettronica', checked: false },
  { id: 'c27', name: 'Fotocamera', category: 'Elettronica', checked: false },
  { id: 'c28', name: 'E-reader / Tablet', category: 'Elettronica', checked: false },
  { id: 'c29', name: 'Spazzolino', category: 'Toilette', checked: false },
  { id: 'c30', name: 'Dentifricio', category: 'Toilette', checked: false },
  { id: 'c31', name: 'Shampoo', category: 'Toilette', checked: false },
  { id: 'c32', name: 'Crema solare', category: 'Toilette', checked: false },
  { id: 'c33', name: 'Deodorante', category: 'Toilette', checked: false },
  { id: 'c34', name: 'Rasoio', category: 'Toilette', checked: false },
  { id: 'c35', name: 'Crema idratante', category: 'Toilette', checked: false },
  { id: 'c36', name: 'Salviette umidificate', category: 'Toilette', checked: false },
];
