import { CurrencyRate } from '@/types';

export const currencies: CurrencyRate[] = [
  { code: 'EUR', name: 'Euro', rate: 1.0, flag: '🇪🇺' },
  { code: 'USD', name: 'Dollaro Statunitense', rate: 1.08, flag: '🇺🇸' },
  { code: 'GBP', name: 'Sterlina Britannica', rate: 0.85, flag: '🇬🇧' },
  { code: 'JPY', name: 'Yen Giapponese', rate: 158.5, flag: '🇯🇵' },
  { code: 'CHF', name: 'Franco Svizzero', rate: 0.95, flag: '🇨🇭' },
  { code: 'AUD', name: 'Dollaro Australiano', rate: 1.65, flag: '🇦🇺' },
  { code: 'CAD', name: 'Dollaro Canadese', rate: 1.47, flag: '🇨🇦' },
  { code: 'THB', name: 'Baht Thailandese', rate: 37.8, flag: '🇹🇭' },
  { code: 'CNY', name: 'Yuan Cinese', rate: 7.82, flag: '🇨🇳' },
  { code: 'INR', name: 'Rupia Indiana', rate: 90.2, flag: '🇮🇳' },
  { code: 'BRL', name: 'Real Brasiliano', rate: 5.35, flag: '🇧🇷' },
  { code: 'MXN', name: 'Peso Messicano', rate: 18.5, flag: '🇲🇽' },
  { code: 'KRW', name: 'Won Sudcoreano', rate: 1420.0, flag: '🇰🇷' },
  { code: 'SEK', name: 'Corona Svedese', rate: 11.2, flag: '🇸🇪' },
  { code: 'NOK', name: 'Corona Norvegese', rate: 11.5, flag: '🇳🇴' },
  { code: 'DKK', name: 'Corona Danese', rate: 7.46, flag: '🇩🇰' },
  { code: 'PLN', name: 'Złoty Polacco', rate: 4.32, flag: '🇵🇱' },
  { code: 'CZK', name: 'Corona Ceca', rate: 24.8, flag: '🇨🇿' },
  { code: 'HUF', name: 'Fiorino Ungherese', rate: 385.0, flag: '🇭🇺' },
  { code: 'RON', name: 'Leu Rumeno', rate: 4.97, flag: '🇷🇴' },
  { code: 'HRK', name: 'Kuna Croata', rate: 7.53, flag: '🇭🇷' },
  { code: 'TRY', name: 'Lira Turca', rate: 32.5, flag: '🇹🇷' },
  { code: 'RUB', name: 'Rublo Russo', rate: 98.0, flag: '🇷🇺' },
  { code: 'ZAR', name: 'Rand Sudafricano', rate: 20.3, flag: '🇿🇦' },
  { code: 'AED', name: 'Dirham Emirati', rate: 3.97, flag: '🇦🇪' },
  { code: 'SAR', name: 'Riyal Saudita', rate: 4.05, flag: '🇸🇦' },
  { code: 'QAR', name: 'Riyal Qatariota', rate: 3.93, flag: '🇶🇦' },
  { code: 'EGP', name: 'Sterlina Egiziana', rate: 33.4, flag: '🇪🇬' },
  { code: 'MAD', name: 'Dirham Marocchino', rate: 10.8, flag: '🇲🇦' },
  { code: 'NZD', name: 'Dollaro Neozelandese', rate: 1.78, flag: '🇳🇿' },
  { code: 'SGD', name: 'Dollaro di Singapore', rate: 1.45, flag: '🇸🇬' },
  { code: 'MYR', name: 'Ringgit Malese', rate: 5.05, flag: '🇲🇾' },
  { code: 'IDR', name: 'Rupia Indonesiana', rate: 16800.0, flag: '🇮🇩' },
  { code: 'PHP', name: 'Peso Filippino', rate: 60.5, flag: '🇵🇭' },
  { code: 'VND', name: 'Dong Vietnamita', rate: 26500.0, flag: '🇻🇳' },
  { code: 'TWD', name: 'Dollaro Taiwanese', rate: 34.0, flag: '🇹🇼' },
  { code: 'ARS', name: 'Peso Argentino', rate: 920.0, flag: '🇦🇷' },
  { code: 'CLP', name: 'Peso Cileno', rate: 980.0, flag: '🇨🇱' },
  { code: 'COP', name: 'Peso Colombiano', rate: 4250.0, flag: '🇨🇴' },
  { code: 'PEN', name: 'Sol Peruviano', rate: 4.0, flag: '🇵🇪' },
  { code: 'ILS', name: 'Shekel Israeliano', rate: 3.95, flag: '🇮🇱' },
  { code: 'NGN', name: 'Naira Nigeriana', rate: 1580.0, flag: '🇳🇬' },
  { code: 'KES', name: 'Scellino Keniota', rate: 155.0, flag: '🇰🇪' },
  { code: 'GHS', name: 'Cedi Ghanese', rate: 13.5, flag: '🇬🇭' },
  { code: 'TND', name: 'Dinaro Tunisino', rate: 3.35, flag: '🇹🇳' },
  { code: 'ISK', name: 'Corona Islandese', rate: 149.0, flag: '🇮🇸' },
  { code: 'BGN', name: 'Lev Bulgaro', rate: 1.96, flag: '🇧🇬' },
  { code: 'RSD', name: 'Dinaro Serbo', rate: 117.0, flag: '🇷🇸' },
  { code: 'GEL', name: 'Lari Georgiano', rate: 2.9, flag: '🇬🇪' },
  { code: 'UAH', name: 'Grivnia Ucraina', rate: 40.0, flag: '🇺🇦' },
];
