import { Phrase } from '@/types';

export const phrases: Phrase[] = [
  { id: 'p1', italian: 'Ciao', english: 'Hello', phonetic: '[chah-oh]', category: 'Base', favorite: false },
  { id: 'p2', italian: 'Buongiorno', english: 'Good morning', phonetic: '[bwon-jor-no]', category: 'Base', favorite: false },
  { id: 'p3', italian: 'Buonasera', english: 'Good evening', phonetic: '[bwon-ah-seh-rah]', category: 'Base', favorite: false },
  { id: 'p4', italian: 'Grazie', english: 'Thank you', phonetic: '[grah-tsee-eh]', category: 'Base', favorite: false },
  { id: 'p5', italian: 'Per favore', english: 'Please', phonetic: '[per fah-voh-reh]', category: 'Base', favorite: false },
  { id: 'p6', italian: 'Mi scusi', english: 'Excuse me', phonetic: '[mee skoo-zee]', category: 'Base', favorite: false },
  { id: 'p7', italian: 'Dove si trova...?', english: 'Where is...?', phonetic: '[doh-veh see troh-vah]', category: 'Base', favorite: false },
  { id: 'p8', italian: 'Quanto costa?', english: 'How much does it cost?', phonetic: '[kwahn-toh koh-stah]', category: 'Base', favorite: false },
  { id: 'p9', italian: 'Sì', english: 'Yes', phonetic: '[see]', category: 'Base', favorite: false },
  { id: 'p10', italian: 'No', english: 'No', phonetic: '[noh]', category: 'Base', favorite: false },
  { id: 'p11', italian: 'Non capisco', english: "I don't understand", phonetic: '[non kah-pee-skoh]', category: 'Base', favorite: false },
  { id: 'p12', italian: 'Parla inglese?', english: 'Do you speak English?', phonetic: '[par-lah een-gleh-zeh]', category: 'Base', favorite: false },
  { id: 'p13', italian: 'Arrivederci', english: 'Goodbye', phonetic: '[ah-ree-veh-der-chee]', category: 'Base', favorite: false },
  { id: 'p14', italian: 'Come stai?', english: 'How are you?', phonetic: '[koh-meh stah-ee]', category: 'Base', favorite: false },
  { id: 'p15', italian: 'Bene, grazie', english: 'Fine, thank you', phonetic: '[beh-neh grah-tsee-eh]', category: 'Base', favorite: false },
  { id: 'p16', italian: 'Il conto, per favore', english: 'The bill, please', phonetic: '[eel kon-toh per fah-voh-reh]', category: 'Ristorante', favorite: false },
  { id: 'p17', italian: 'Un tavolo per due', english: 'A table for two', phonetic: '[oon tah-voh-loh per doo-eh]', category: 'Ristorante', favorite: false },
  { id: 'p18', italian: 'Sono allergico a...', english: "I'm allergic to...", phonetic: '[soh-noh ah-ler-jee-koh ah]', category: 'Ristorante', favorite: false },
  { id: 'p19', italian: 'Acqua, per favore', english: 'Water, please', phonetic: '[ah-kwah per fah-voh-reh]', category: 'Ristorante', favorite: false },
  { id: 'p20', italian: 'Il menù, per favore', english: 'The menu, please', phonetic: '[eel meh-noo per fah-voh-reh]', category: 'Ristorante', favorite: false },
  { id: 'p21', italian: 'Vorrei ordinare...', english: 'I would like to order...', phonetic: '[vor-ray or-dee-nah-reh]', category: 'Ristorante', favorite: false },
  { id: 'p22', italian: 'È buonissimo!', english: "It's delicious!", phonetic: '[eh bwoh-nee-see-moh]', category: 'Ristorante', favorite: false },
  { id: 'p23', italian: 'Sono vegetariano/a', english: "I'm vegetarian", phonetic: '[soh-noh veh-jeh-tah-ree-ah-noh]', category: 'Ristorante', favorite: false },
  { id: 'p24', italian: 'Un caffè, per favore', english: 'A coffee, please', phonetic: '[oon kaf-feh per fah-voh-reh]', category: 'Ristorante', favorite: false },
  { id: 'p25', italian: 'Quanto costa questo?', english: 'How much is this?', phonetic: '[kwahn-toh koh-stah kweh-stoh]', category: 'Shopping', favorite: false },
  { id: 'p26', italian: 'Posso provare?', english: 'Can I try it on?', phonetic: '[poh-soh proh-vah-reh]', category: 'Shopping', favorite: false },
  { id: 'p27', italian: 'Accettate carta di credito?', english: 'Do you accept credit card?', phonetic: '[ah-chet-tah-teh kar-tah dee kreh-dee-toh]', category: 'Shopping', favorite: false },
  { id: 'p28', italian: 'Troppo caro', english: 'Too expensive', phonetic: '[troh-poh kah-roh]', category: 'Shopping', favorite: false },
  { id: 'p29', italian: 'Avete una taglia più grande?', english: 'Do you have a bigger size?', phonetic: '[ah-veh-teh oo-nah tah-lyah pyoo gran-deh]', category: 'Shopping', favorite: false },
  { id: 'p30', italian: 'Dove sono i camerini?', english: 'Where are the fitting rooms?', phonetic: '[doh-veh soh-noh ee kah-meh-ree-nee]', category: 'Shopping', favorite: false },
  { id: 'p31', italian: 'Uno sconto?', english: 'A discount?', phonetic: '[oo-noh skon-toh]', category: 'Shopping', favorite: false },
  { id: 'p32', italian: 'Lo prendo', english: "I'll take it", phonetic: '[loh pren-doh]', category: 'Shopping', favorite: false },
  { id: 'p33', italian: 'Aiuto!', english: 'Help!', phonetic: '[ah-yoo-toh]', category: 'Emergenza', favorite: false },
  { id: 'p34', italian: 'Chiama la polizia!', english: 'Call the police!', phonetic: '[kyah-mah lah poh-lee-tsee-ah]', category: 'Emergenza', favorite: false },
  { id: 'p35', italian: "Dov'è l'ospedale?", english: 'Where is the hospital?', phonetic: '[doh-veh loh-speh-dah-leh]', category: 'Emergenza', favorite: false },
  { id: 'p36', italian: 'Mi sento male', english: "I feel sick", phonetic: '[mee sen-toh mah-leh]', category: 'Emergenza', favorite: false },
  { id: 'p37', italian: 'Ho bisogno di un medico', english: 'I need a doctor', phonetic: '[oh bee-zoh-nyoh dee oon meh-dee-koh]', category: 'Emergenza', favorite: false },
  { id: 'p38', italian: 'Ho perso il passaporto', english: 'I lost my passport', phonetic: '[oh per-soh eel pah-sah-por-toh]', category: 'Emergenza', favorite: false },
  { id: 'p39', italian: "C'è stato un incidente", english: 'There has been an accident', phonetic: '[cheh stah-toh oon een-chee-den-teh]', category: 'Emergenza', favorite: false },
  { id: 'p40', italian: 'Sono perduto/a', english: "I'm lost", phonetic: '[soh-noh per-doo-toh]', category: 'Emergenza', favorite: false },
  { id: 'p41', italian: "Dov'è la stazione?", english: 'Where is the station?', phonetic: '[doh-veh lah stah-tsyoh-neh]', category: 'Trasporti', favorite: false },
  { id: 'p42', italian: "Dov'è l'aeroporto?", english: 'Where is the airport?', phonetic: '[doh-veh lah-eh-roh-por-toh]', category: 'Trasporti', favorite: false },
  { id: 'p43', italian: 'Un biglietto per...', english: 'A ticket to...', phonetic: '[oon bee-lyet-toh per]', category: 'Trasporti', favorite: false },
  { id: 'p44', italian: 'Dove va questo treno?', english: 'Where does this train go?', phonetic: '[doh-veh vah kweh-stoh treh-noh]', category: 'Trasporti', favorite: false },
  { id: 'p45', italian: 'Mi può chiamare un taxi?', english: 'Can you call me a taxi?', phonetic: '[mee pwoh kyah-mah-reh oon tak-see]', category: 'Trasporti', favorite: false },
  { id: 'p46', italian: 'A che ora parte?', english: 'What time does it leave?', phonetic: '[ah keh oh-rah par-teh]', category: 'Trasporti', favorite: false },
  { id: 'p47', italian: 'Fermata successiva?', english: 'Next stop?', phonetic: '[fer-mah-tah soo-ches-see-vah]', category: 'Trasporti', favorite: false },
  { id: 'p48', italian: 'Andata e ritorno', english: 'Round trip', phonetic: '[an-dah-tah eh ree-tor-noh]', category: 'Trasporti', favorite: false },
];
