import { ClimateDestination } from '@/types';

export const climateDestinations: ClimateDestination[] = [
  {
    id: 'cl1',
    country: 'Thailandia',
    flag: '🇹🇭',
    city: 'Bangkok',
    quickTip: 'Visita Bangkok: evita maggio-ottobre (monsoni), scegli novembre-febbraio',
    months: [
      { month: 'Gennaio', monthShort: 'Gen', tempMin: 21, tempMax: 32, precipitation: 10, condition: 'sunny', conditionLabel: 'Soleggiato', isBest: true, isWorst: false },
      { month: 'Febbraio', monthShort: 'Feb', tempMin: 23, tempMax: 33, precipitation: 20, condition: 'sunny', conditionLabel: 'Soleggiato', isBest: true, isWorst: false },
      { month: 'Marzo', monthShort: 'Mar', tempMin: 25, tempMax: 34, precipitation: 30, condition: 'sunny', conditionLabel: 'Caldo', isBest: false, isWorst: false },
      { month: 'Aprile', monthShort: 'Apr', tempMin: 26, tempMax: 35, precipitation: 65, condition: 'humid', conditionLabel: 'Caldo umido', isBest: false, isWorst: false },
      { month: 'Maggio', monthShort: 'Mag', tempMin: 25, tempMax: 34, precipitation: 190, condition: 'rainy', conditionLabel: 'Piogge', isBest: false, isWorst: true, worstReason: 'Inizio monsoni' },
      { month: 'Giugno', monthShort: 'Giu', tempMin: 25, tempMax: 33, precipitation: 150, condition: 'rainy', conditionLabel: 'Monsoni', isBest: false, isWorst: true, worstReason: 'Monsoni intensi' },
      { month: 'Luglio', monthShort: 'Lug', tempMin: 25, tempMax: 33, precipitation: 160, condition: 'stormy', conditionLabel: 'Monsoni', isBest: false, isWorst: true, worstReason: 'Monsoni intensi' },
      { month: 'Agosto', monthShort: 'Ago', tempMin: 25, tempMax: 33, precipitation: 175, condition: 'stormy', conditionLabel: 'Monsoni', isBest: false, isWorst: true, worstReason: 'Monsoni e alluvioni' },
      { month: 'Settembre', monthShort: 'Set', tempMin: 24, tempMax: 32, precipitation: 320, condition: 'stormy', conditionLabel: 'Piogge intense', isBest: false, isWorst: true, worstReason: 'Picco piogge' },
      { month: 'Ottobre', monthShort: 'Ott', tempMin: 24, tempMax: 32, precipitation: 240, condition: 'rainy', conditionLabel: 'Piogge', isBest: false, isWorst: true, worstReason: 'Fine monsoni' },
      { month: 'Novembre', monthShort: 'Nov', tempMin: 22, tempMax: 32, precipitation: 50, condition: 'partly_cloudy', conditionLabel: 'Mite', isBest: true, isWorst: false },
      { month: 'Dicembre', monthShort: 'Dic', tempMin: 20, tempMax: 31, precipitation: 10, condition: 'sunny', conditionLabel: 'Soleggiato', isBest: true, isWorst: false },
    ],
  },
  {
    id: 'cl2',
    country: 'Italia',
    flag: '🇮🇹',
    city: 'Roma',
    quickTip: 'Visita Roma: ideale aprile-giugno e settembre-ottobre, evita agosto (caldo e folla)',
    months: [
      { month: 'Gennaio', monthShort: 'Gen', tempMin: 3, tempMax: 12, precipitation: 70, condition: 'cloudy', conditionLabel: 'Freddo', isBest: false, isWorst: false },
      { month: 'Febbraio', monthShort: 'Feb', tempMin: 3, tempMax: 13, precipitation: 60, condition: 'cloudy', conditionLabel: 'Freddo', isBest: false, isWorst: false },
      { month: 'Marzo', monthShort: 'Mar', tempMin: 5, tempMax: 16, precipitation: 55, condition: 'partly_cloudy', conditionLabel: 'Mite', isBest: false, isWorst: false },
      { month: 'Aprile', monthShort: 'Apr', tempMin: 8, tempMax: 19, precipitation: 50, condition: 'partly_cloudy', conditionLabel: 'Piacevole', isBest: true, isWorst: false },
      { month: 'Maggio', monthShort: 'Mag', tempMin: 12, tempMax: 24, precipitation: 40, condition: 'sunny', conditionLabel: 'Soleggiato', isBest: true, isWorst: false },
      { month: 'Giugno', monthShort: 'Giu', tempMin: 16, tempMax: 28, precipitation: 20, condition: 'sunny', conditionLabel: 'Caldo', isBest: true, isWorst: false },
      { month: 'Luglio', monthShort: 'Lug', tempMin: 19, tempMax: 32, precipitation: 10, condition: 'sunny', conditionLabel: 'Molto caldo', isBest: false, isWorst: false },
      { month: 'Agosto', monthShort: 'Ago', tempMin: 19, tempMax: 32, precipitation: 20, condition: 'sunny', conditionLabel: 'Molto caldo', isBest: false, isWorst: true, worstReason: 'Caldo estremo e folla turistica' },
      { month: 'Settembre', monthShort: 'Set', tempMin: 16, tempMax: 28, precipitation: 65, condition: 'partly_cloudy', conditionLabel: 'Piacevole', isBest: true, isWorst: false },
      { month: 'Ottobre', monthShort: 'Ott', tempMin: 12, tempMax: 23, precipitation: 95, condition: 'partly_cloudy', conditionLabel: 'Mite', isBest: true, isWorst: false },
      { month: 'Novembre', monthShort: 'Nov', tempMin: 7, tempMax: 17, precipitation: 105, condition: 'rainy', conditionLabel: 'Piogge', isBest: false, isWorst: false },
      { month: 'Dicembre', monthShort: 'Dic', tempMin: 4, tempMax: 13, precipitation: 80, condition: 'cloudy', conditionLabel: 'Freddo', isBest: false, isWorst: false },
    ],
  },
  {
    id: 'cl3',
    country: 'Giappone',
    flag: '🇯🇵',
    city: 'Tokyo',
    quickTip: 'Visita Tokyo: marzo-maggio (ciliegi) o ottobre-novembre (foliage), evita giugno-luglio (piogge)',
    months: [
      { month: 'Gennaio', monthShort: 'Gen', tempMin: 1, tempMax: 10, precipitation: 50, condition: 'sunny', conditionLabel: 'Freddo secco', isBest: false, isWorst: false },
      { month: 'Febbraio', monthShort: 'Feb', tempMin: 2, tempMax: 11, precipitation: 55, condition: 'sunny', conditionLabel: 'Freddo', isBest: false, isWorst: false },
      { month: 'Marzo', monthShort: 'Mar', tempMin: 5, tempMax: 14, precipitation: 115, condition: 'partly_cloudy', conditionLabel: 'Ciliegi in fiore', isBest: true, isWorst: false },
      { month: 'Aprile', monthShort: 'Apr', tempMin: 10, tempMax: 19, precipitation: 130, condition: 'partly_cloudy', conditionLabel: 'Piacevole', isBest: true, isWorst: false },
      { month: 'Maggio', monthShort: 'Mag', tempMin: 15, tempMax: 24, precipitation: 140, condition: 'partly_cloudy', conditionLabel: 'Piacevole', isBest: true, isWorst: false },
      { month: 'Giugno', monthShort: 'Giu', tempMin: 19, tempMax: 26, precipitation: 165, condition: 'rainy', conditionLabel: 'Stagione piogge', isBest: false, isWorst: true, worstReason: 'Tsuyu (stagione delle piogge)' },
      { month: 'Luglio', monthShort: 'Lug', tempMin: 23, tempMax: 30, precipitation: 155, condition: 'humid', conditionLabel: 'Caldo umido', isBest: false, isWorst: true, worstReason: 'Caldo umido intenso' },
      { month: 'Agosto', monthShort: 'Ago', tempMin: 24, tempMax: 31, precipitation: 170, condition: 'humid', conditionLabel: 'Caldo umido', isBest: false, isWorst: true, worstReason: 'Caldo umido e tifoni' },
      { month: 'Settembre', monthShort: 'Set', tempMin: 20, tempMax: 27, precipitation: 210, condition: 'rainy', conditionLabel: 'Tifoni', isBest: false, isWorst: false },
      { month: 'Ottobre', monthShort: 'Ott', tempMin: 14, tempMax: 22, precipitation: 200, condition: 'partly_cloudy', conditionLabel: 'Foliage', isBest: true, isWorst: false },
      { month: 'Novembre', monthShort: 'Nov', tempMin: 8, tempMax: 17, precipitation: 95, condition: 'sunny', conditionLabel: 'Foliage', isBest: true, isWorst: false },
      { month: 'Dicembre', monthShort: 'Dic', tempMin: 3, tempMax: 12, precipitation: 50, condition: 'sunny', conditionLabel: 'Freddo secco', isBest: false, isWorst: false },
    ],
  },
  {
    id: 'cl4',
    country: 'Stati Uniti',
    flag: '🇺🇸',
    city: 'New York',
    quickTip: 'Visita New York: aprile-giugno e settembre-novembre, evita gennaio-febbraio (gelo) e luglio-agosto (afa)',
    months: [
      { month: 'Gennaio', monthShort: 'Gen', tempMin: -3, tempMax: 4, precipitation: 80, condition: 'snowy', conditionLabel: 'Neve', isBest: false, isWorst: true, worstReason: 'Gelo intenso' },
      { month: 'Febbraio', monthShort: 'Feb', tempMin: -2, tempMax: 5, precipitation: 75, condition: 'snowy', conditionLabel: 'Neve', isBest: false, isWorst: true, worstReason: 'Gelo intenso' },
      { month: 'Marzo', monthShort: 'Mar', tempMin: 2, tempMax: 10, precipitation: 100, condition: 'cloudy', conditionLabel: 'Fresco', isBest: false, isWorst: false },
      { month: 'Aprile', monthShort: 'Apr', tempMin: 7, tempMax: 17, precipitation: 100, condition: 'partly_cloudy', conditionLabel: 'Piacevole', isBest: true, isWorst: false },
      { month: 'Maggio', monthShort: 'Mag', tempMin: 12, tempMax: 22, precipitation: 105, condition: 'sunny', conditionLabel: 'Piacevole', isBest: true, isWorst: false },
      { month: 'Giugno', monthShort: 'Giu', tempMin: 18, tempMax: 27, precipitation: 110, condition: 'sunny', conditionLabel: 'Caldo', isBest: true, isWorst: false },
      { month: 'Luglio', monthShort: 'Lug', tempMin: 21, tempMax: 30, precipitation: 115, condition: 'humid', conditionLabel: 'Afoso', isBest: false, isWorst: false },
      { month: 'Agosto', monthShort: 'Ago', tempMin: 20, tempMax: 29, precipitation: 110, condition: 'humid', conditionLabel: 'Afoso', isBest: false, isWorst: false },
      { month: 'Settembre', monthShort: 'Set', tempMin: 16, tempMax: 25, precipitation: 105, condition: 'sunny', conditionLabel: 'Piacevole', isBest: true, isWorst: false },
      { month: 'Ottobre', monthShort: 'Ott', tempMin: 10, tempMax: 18, precipitation: 90, condition: 'partly_cloudy', conditionLabel: 'Foliage', isBest: true, isWorst: false },
      { month: 'Novembre', monthShort: 'Nov', tempMin: 5, tempMax: 13, precipitation: 85, condition: 'cloudy', conditionLabel: 'Fresco', isBest: true, isWorst: false },
      { month: 'Dicembre', monthShort: 'Dic', tempMin: -1, tempMax: 6, precipitation: 90, condition: 'snowy', conditionLabel: 'Neve', isBest: false, isWorst: false },
    ],
  },
  {
    id: 'cl5',
    country: 'Emirati Arabi',
    flag: '🇦🇪',
    city: 'Dubai',
    quickTip: 'Visita Dubai: novembre-marzo (clima perfetto), evita giugno-settembre (caldo estremo 45°C+)',
    months: [
      { month: 'Gennaio', monthShort: 'Gen', tempMin: 14, tempMax: 24, precipitation: 10, condition: 'sunny', conditionLabel: 'Perfetto', isBest: true, isWorst: false },
      { month: 'Febbraio', monthShort: 'Feb', tempMin: 15, tempMax: 25, precipitation: 35, condition: 'sunny', conditionLabel: 'Perfetto', isBest: true, isWorst: false },
      { month: 'Marzo', monthShort: 'Mar', tempMin: 17, tempMax: 29, precipitation: 20, condition: 'sunny', conditionLabel: 'Caldo', isBest: true, isWorst: false },
      { month: 'Aprile', monthShort: 'Apr', tempMin: 21, tempMax: 34, precipitation: 5, condition: 'sunny', conditionLabel: 'Caldo', isBest: false, isWorst: false },
      { month: 'Maggio', monthShort: 'Mag', tempMin: 25, tempMax: 39, precipitation: 0, condition: 'sunny', conditionLabel: 'Molto caldo', isBest: false, isWorst: false },
      { month: 'Giugno', monthShort: 'Giu', tempMin: 28, tempMax: 41, precipitation: 0, condition: 'sunny', conditionLabel: 'Estremo', isBest: false, isWorst: true, worstReason: 'Caldo estremo 40°C+' },
      { month: 'Luglio', monthShort: 'Lug', tempMin: 30, tempMax: 43, precipitation: 0, condition: 'sunny', conditionLabel: 'Estremo', isBest: false, isWorst: true, worstReason: 'Caldo estremo 43°C+' },
      { month: 'Agosto', monthShort: 'Ago', tempMin: 31, tempMax: 43, precipitation: 0, condition: 'humid', conditionLabel: 'Estremo umido', isBest: false, isWorst: true, worstReason: 'Caldo estremo e umidità' },
      { month: 'Settembre', monthShort: 'Set', tempMin: 27, tempMax: 40, precipitation: 0, condition: 'sunny', conditionLabel: 'Molto caldo', isBest: false, isWorst: true, worstReason: 'Ancora molto caldo' },
      { month: 'Ottobre', monthShort: 'Ott', tempMin: 23, tempMax: 36, precipitation: 0, condition: 'sunny', conditionLabel: 'Caldo', isBest: false, isWorst: false },
      { month: 'Novembre', monthShort: 'Nov', tempMin: 19, tempMax: 30, precipitation: 5, condition: 'sunny', conditionLabel: 'Piacevole', isBest: true, isWorst: false },
      { month: 'Dicembre', monthShort: 'Dic', tempMin: 15, tempMax: 26, precipitation: 10, condition: 'sunny', conditionLabel: 'Perfetto', isBest: true, isWorst: false },
    ],
  },
  {
    id: 'cl6',
    country: 'Spagna',
    flag: '🇪🇸',
    city: 'Barcellona',
    quickTip: 'Visita Barcellona: maggio-giugno e settembre-ottobre, evita agosto (folla e caldo)',
    months: [
      { month: 'Gennaio', monthShort: 'Gen', tempMin: 5, tempMax: 13, precipitation: 40, condition: 'cloudy', conditionLabel: 'Fresco', isBest: false, isWorst: false },
      { month: 'Febbraio', monthShort: 'Feb', tempMin: 6, tempMax: 14, precipitation: 30, condition: 'partly_cloudy', conditionLabel: 'Fresco', isBest: false, isWorst: false },
      { month: 'Marzo', monthShort: 'Mar', tempMin: 8, tempMax: 16, precipitation: 35, condition: 'partly_cloudy', conditionLabel: 'Mite', isBest: false, isWorst: false },
      { month: 'Aprile', monthShort: 'Apr', tempMin: 10, tempMax: 18, precipitation: 45, condition: 'partly_cloudy', conditionLabel: 'Piacevole', isBest: false, isWorst: false },
      { month: 'Maggio', monthShort: 'Mag', tempMin: 14, tempMax: 22, precipitation: 50, condition: 'sunny', conditionLabel: 'Perfetto', isBest: true, isWorst: false },
      { month: 'Giugno', monthShort: 'Giu', tempMin: 18, tempMax: 26, precipitation: 30, condition: 'sunny', conditionLabel: 'Caldo', isBest: true, isWorst: false },
      { month: 'Luglio', monthShort: 'Lug', tempMin: 21, tempMax: 29, precipitation: 20, condition: 'sunny', conditionLabel: 'Molto caldo', isBest: false, isWorst: false },
      { month: 'Agosto', monthShort: 'Ago', tempMin: 21, tempMax: 29, precipitation: 55, condition: 'humid', conditionLabel: 'Caldo afoso', isBest: false, isWorst: true, worstReason: 'Alta stagione, folla e caldo' },
      { month: 'Settembre', monthShort: 'Set', tempMin: 18, tempMax: 26, precipitation: 80, condition: 'partly_cloudy', conditionLabel: 'Piacevole', isBest: true, isWorst: false },
      { month: 'Ottobre', monthShort: 'Ott', tempMin: 14, tempMax: 22, precipitation: 90, condition: 'partly_cloudy', conditionLabel: 'Mite', isBest: true, isWorst: false },
      { month: 'Novembre', monthShort: 'Nov', tempMin: 9, tempMax: 17, precipitation: 55, condition: 'rainy', conditionLabel: 'Piogge', isBest: false, isWorst: false },
      { month: 'Dicembre', monthShort: 'Dic', tempMin: 6, tempMax: 14, precipitation: 40, condition: 'cloudy', conditionLabel: 'Fresco', isBest: false, isWorst: false },
    ],
  },
  {
    id: 'cl7',
    country: 'Francia',
    flag: '🇫🇷',
    city: 'Parigi',
    quickTip: 'Visita Parigi: aprile-giugno e settembre-ottobre, evita agosto (folla) e novembre-febbraio (grigio)',
    months: [
      { month: 'Gennaio', monthShort: 'Gen', tempMin: 1, tempMax: 7, precipitation: 50, condition: 'cloudy', conditionLabel: 'Grigio freddo', isBest: false, isWorst: true, worstReason: 'Freddo e grigio' },
      { month: 'Febbraio', monthShort: 'Feb', tempMin: 1, tempMax: 8, precipitation: 40, condition: 'cloudy', conditionLabel: 'Grigio freddo', isBest: false, isWorst: true, worstReason: 'Freddo e grigio' },
      { month: 'Marzo', monthShort: 'Mar', tempMin: 4, tempMax: 12, precipitation: 45, condition: 'partly_cloudy', conditionLabel: 'Mite', isBest: false, isWorst: false },
      { month: 'Aprile', monthShort: 'Apr', tempMin: 6, tempMax: 16, precipitation: 45, condition: 'partly_cloudy', conditionLabel: 'Piacevole', isBest: true, isWorst: false },
      { month: 'Maggio', monthShort: 'Mag', tempMin: 10, tempMax: 20, precipitation: 60, condition: 'sunny', conditionLabel: 'Perfetto', isBest: true, isWorst: false },
      { month: 'Giugno', monthShort: 'Giu', tempMin: 13, tempMax: 24, precipitation: 50, condition: 'sunny', conditionLabel: 'Soleggiato', isBest: true, isWorst: false },
      { month: 'Luglio', monthShort: 'Lug', tempMin: 15, tempMax: 26, precipitation: 55, condition: 'sunny', conditionLabel: 'Caldo', isBest: false, isWorst: false },
      { month: 'Agosto', monthShort: 'Ago', tempMin: 15, tempMax: 26, precipitation: 50, condition: 'sunny', conditionLabel: 'Caldo', isBest: false, isWorst: true, worstReason: 'Alta stagione turistica' },
      { month: 'Settembre', monthShort: 'Set', tempMin: 12, tempMax: 22, precipitation: 45, condition: 'partly_cloudy', conditionLabel: 'Piacevole', isBest: true, isWorst: false },
      { month: 'Ottobre', monthShort: 'Ott', tempMin: 8, tempMax: 17, precipitation: 55, condition: 'partly_cloudy', conditionLabel: 'Foliage', isBest: true, isWorst: false },
      { month: 'Novembre', monthShort: 'Nov', tempMin: 4, tempMax: 11, precipitation: 50, condition: 'cloudy', conditionLabel: 'Grigio', isBest: false, isWorst: false },
      { month: 'Dicembre', monthShort: 'Dic', tempMin: 2, tempMax: 8, precipitation: 55, condition: 'cloudy', conditionLabel: 'Freddo', isBest: false, isWorst: false },
    ],
  },
  {
    id: 'cl8',
    country: 'Regno Unito',
    flag: '🇬🇧',
    city: 'Londra',
    quickTip: 'Visita Londra: maggio-settembre, evita novembre-febbraio (freddo, pioggia e buio)',
    months: [
      { month: 'Gennaio', monthShort: 'Gen', tempMin: 2, tempMax: 8, precipitation: 55, condition: 'cloudy', conditionLabel: 'Freddo grigio', isBest: false, isWorst: true, worstReason: 'Freddo, pioggia e poche ore di luce' },
      { month: 'Febbraio', monthShort: 'Feb', tempMin: 2, tempMax: 9, precipitation: 40, condition: 'cloudy', conditionLabel: 'Freddo', isBest: false, isWorst: true, worstReason: 'Ancora freddo e grigio' },
      { month: 'Marzo', monthShort: 'Mar', tempMin: 4, tempMax: 12, precipitation: 40, condition: 'partly_cloudy', conditionLabel: 'Fresco', isBest: false, isWorst: false },
      { month: 'Aprile', monthShort: 'Apr', tempMin: 5, tempMax: 15, precipitation: 40, condition: 'partly_cloudy', conditionLabel: 'Mite', isBest: false, isWorst: false },
      { month: 'Maggio', monthShort: 'Mag', tempMin: 8, tempMax: 18, precipitation: 45, condition: 'partly_cloudy', conditionLabel: 'Piacevole', isBest: true, isWorst: false },
      { month: 'Giugno', monthShort: 'Giu', tempMin: 12, tempMax: 22, precipitation: 45, condition: 'sunny', conditionLabel: 'Soleggiato', isBest: true, isWorst: false },
      { month: 'Luglio', monthShort: 'Lug', tempMin: 14, tempMax: 24, precipitation: 45, condition: 'sunny', conditionLabel: 'Caldo', isBest: true, isWorst: false },
      { month: 'Agosto', monthShort: 'Ago', tempMin: 13, tempMax: 23, precipitation: 50, condition: 'partly_cloudy', conditionLabel: 'Piacevole', isBest: true, isWorst: false },
      { month: 'Settembre', monthShort: 'Set', tempMin: 11, tempMax: 20, precipitation: 50, condition: 'partly_cloudy', conditionLabel: 'Mite', isBest: true, isWorst: false },
      { month: 'Ottobre', monthShort: 'Ott', tempMin: 8, tempMax: 16, precipitation: 60, condition: 'cloudy', conditionLabel: 'Fresco', isBest: false, isWorst: false },
      { month: 'Novembre', monthShort: 'Nov', tempMin: 5, tempMax: 11, precipitation: 60, condition: 'rainy', conditionLabel: 'Pioggia', isBest: false, isWorst: true, worstReason: 'Pioggia e buio' },
      { month: 'Dicembre', monthShort: 'Dic', tempMin: 3, tempMax: 9, precipitation: 55, condition: 'cloudy', conditionLabel: 'Freddo', isBest: false, isWorst: false },
    ],
  },
  {
    id: 'cl9',
    country: 'Australia',
    flag: '🇦🇺',
    city: 'Sydney',
    quickTip: 'Visita Sydney: settembre-novembre e marzo-maggio, evita gennaio (caldo estremo e incendi)',
    months: [
      { month: 'Gennaio', monthShort: 'Gen', tempMin: 19, tempMax: 27, precipitation: 100, condition: 'humid', conditionLabel: 'Caldo umido', isBest: false, isWorst: true, worstReason: 'Caldo estremo, rischio incendi' },
      { month: 'Febbraio', monthShort: 'Feb', tempMin: 19, tempMax: 27, precipitation: 115, condition: 'humid', conditionLabel: 'Caldo umido', isBest: false, isWorst: false },
      { month: 'Marzo', monthShort: 'Mar', tempMin: 18, tempMax: 26, precipitation: 125, condition: 'partly_cloudy', conditionLabel: 'Piacevole', isBest: true, isWorst: false },
      { month: 'Aprile', monthShort: 'Apr', tempMin: 14, tempMax: 23, precipitation: 125, condition: 'partly_cloudy', conditionLabel: 'Mite', isBest: true, isWorst: false },
      { month: 'Maggio', monthShort: 'Mag', tempMin: 11, tempMax: 20, precipitation: 120, condition: 'partly_cloudy', conditionLabel: 'Fresco', isBest: true, isWorst: false },
      { month: 'Giugno', monthShort: 'Giu', tempMin: 9, tempMax: 18, precipitation: 130, condition: 'cloudy', conditionLabel: 'Inverno mite', isBest: false, isWorst: false },
      { month: 'Luglio', monthShort: 'Lug', tempMin: 8, tempMax: 17, precipitation: 95, condition: 'sunny', conditionLabel: 'Fresco secco', isBest: false, isWorst: false },
      { month: 'Agosto', monthShort: 'Ago', tempMin: 8, tempMax: 18, precipitation: 80, condition: 'sunny', conditionLabel: 'Fresco', isBest: false, isWorst: false },
      { month: 'Settembre', monthShort: 'Set', tempMin: 11, tempMax: 21, precipitation: 65, condition: 'sunny', conditionLabel: 'Primavera', isBest: true, isWorst: false },
      { month: 'Ottobre', monthShort: 'Ott', tempMin: 13, tempMax: 23, precipitation: 75, condition: 'sunny', conditionLabel: 'Piacevole', isBest: true, isWorst: false },
      { month: 'Novembre', monthShort: 'Nov', tempMin: 16, tempMax: 25, precipitation: 85, condition: 'sunny', conditionLabel: 'Soleggiato', isBest: true, isWorst: false },
      { month: 'Dicembre', monthShort: 'Dic', tempMin: 18, tempMax: 26, precipitation: 75, condition: 'sunny', conditionLabel: 'Estate', isBest: false, isWorst: false },
    ],
  },
  {
    id: 'cl10',
    country: 'Brasile',
    flag: '🇧🇷',
    city: 'Rio de Janeiro',
    quickTip: 'Visita Rio: maggio-settembre (inverno secco), evita dicembre-marzo (piogge torrenziali e afa)',
    months: [
      { month: 'Gennaio', monthShort: 'Gen', tempMin: 24, tempMax: 32, precipitation: 135, condition: 'stormy', conditionLabel: 'Piogge forti', isBest: false, isWorst: true, worstReason: 'Piogge torrenziali e afa' },
      { month: 'Febbraio', monthShort: 'Feb', tempMin: 24, tempMax: 33, precipitation: 125, condition: 'stormy', conditionLabel: 'Piogge + Carnevale', isBest: false, isWorst: false },
      { month: 'Marzo', monthShort: 'Mar', tempMin: 23, tempMax: 31, precipitation: 130, condition: 'rainy', conditionLabel: 'Piogge', isBest: false, isWorst: true, worstReason: 'Ancora piogge intense' },
      { month: 'Aprile', monthShort: 'Apr', tempMin: 22, tempMax: 29, precipitation: 105, condition: 'partly_cloudy', conditionLabel: 'Mite', isBest: false, isWorst: false },
      { month: 'Maggio', monthShort: 'Mag', tempMin: 20, tempMax: 27, precipitation: 80, condition: 'sunny', conditionLabel: 'Piacevole', isBest: true, isWorst: false },
      { month: 'Giugno', monthShort: 'Giu', tempMin: 19, tempMax: 26, precipitation: 55, condition: 'sunny', conditionLabel: 'Secco', isBest: true, isWorst: false },
      { month: 'Luglio', monthShort: 'Lug', tempMin: 18, tempMax: 25, precipitation: 40, condition: 'sunny', conditionLabel: 'Fresco secco', isBest: true, isWorst: false },
      { month: 'Agosto', monthShort: 'Ago', tempMin: 19, tempMax: 26, precipitation: 45, condition: 'sunny', conditionLabel: 'Secco', isBest: true, isWorst: false },
      { month: 'Settembre', monthShort: 'Set', tempMin: 19, tempMax: 26, precipitation: 65, condition: 'partly_cloudy', conditionLabel: 'Mite', isBest: true, isWorst: false },
      { month: 'Ottobre', monthShort: 'Ott', tempMin: 20, tempMax: 28, precipitation: 90, condition: 'partly_cloudy', conditionLabel: 'Caldo', isBest: false, isWorst: false },
      { month: 'Novembre', monthShort: 'Nov', tempMin: 22, tempMax: 29, precipitation: 100, condition: 'rainy', conditionLabel: 'Piogge', isBest: false, isWorst: false },
      { month: 'Dicembre', monthShort: 'Dic', tempMin: 23, tempMax: 31, precipitation: 135, condition: 'stormy', conditionLabel: 'Piogge forti', isBest: false, isWorst: true, worstReason: 'Inizio piogge torrenziali' },
    ],
  },
  {
    id: 'cl11',
    country: 'India',
    flag: '🇮🇳',
    city: 'Delhi',
    quickTip: 'Visita Delhi: ottobre-marzo (inverno secco), evita maggio-settembre (monsoni e caldo 45°C)',
    months: [
      { month: 'Gennaio', monthShort: 'Gen', tempMin: 7, tempMax: 21, precipitation: 20, condition: 'sunny', conditionLabel: 'Fresco', isBest: true, isWorst: false },
      { month: 'Febbraio', monthShort: 'Feb', tempMin: 10, tempMax: 24, precipitation: 15, condition: 'sunny', conditionLabel: 'Mite', isBest: true, isWorst: false },
      { month: 'Marzo', monthShort: 'Mar', tempMin: 15, tempMax: 31, precipitation: 10, condition: 'sunny', conditionLabel: 'Caldo', isBest: true, isWorst: false },
      { month: 'Aprile', monthShort: 'Apr', tempMin: 21, tempMax: 38, precipitation: 10, condition: 'sunny', conditionLabel: 'Molto caldo', isBest: false, isWorst: false },
      { month: 'Maggio', monthShort: 'Mag', tempMin: 26, tempMax: 42, precipitation: 15, condition: 'sunny', conditionLabel: 'Estremo', isBest: false, isWorst: true, worstReason: 'Caldo estremo 42°C+' },
      { month: 'Giugno', monthShort: 'Giu', tempMin: 28, tempMax: 40, precipitation: 55, condition: 'humid', conditionLabel: 'Monsone', isBest: false, isWorst: true, worstReason: 'Caldo e inizio monsoni' },
      { month: 'Luglio', monthShort: 'Lug', tempMin: 27, tempMax: 35, precipitation: 210, condition: 'stormy', conditionLabel: 'Monsone', isBest: false, isWorst: true, worstReason: 'Monsoni intensi' },
      { month: 'Agosto', monthShort: 'Ago', tempMin: 26, tempMax: 34, precipitation: 235, condition: 'stormy', conditionLabel: 'Monsone', isBest: false, isWorst: true, worstReason: 'Picco monsoni e alluvioni' },
      { month: 'Settembre', monthShort: 'Set', tempMin: 24, tempMax: 34, precipitation: 125, condition: 'rainy', conditionLabel: 'Fine monsone', isBest: false, isWorst: true, worstReason: 'Ancora piogge monsone' },
      { month: 'Ottobre', monthShort: 'Ott', tempMin: 19, tempMax: 34, precipitation: 15, condition: 'sunny', conditionLabel: 'Piacevole', isBest: true, isWorst: false },
      { month: 'Novembre', monthShort: 'Nov', tempMin: 12, tempMax: 29, precipitation: 5, condition: 'sunny', conditionLabel: 'Secco', isBest: true, isWorst: false },
      { month: 'Dicembre', monthShort: 'Dic', tempMin: 8, tempMax: 23, precipitation: 10, condition: 'sunny', conditionLabel: 'Fresco', isBest: true, isWorst: false },
    ],
  },
  {
    id: 'cl12',
    country: 'Egitto',
    flag: '🇪🇬',
    city: 'Il Cairo',
    quickTip: 'Visita Il Cairo: ottobre-aprile, evita giugno-agosto (caldo estremo 40°C+)',
    months: [
      { month: 'Gennaio', monthShort: 'Gen', tempMin: 9, tempMax: 19, precipitation: 5, condition: 'sunny', conditionLabel: 'Mite', isBest: true, isWorst: false },
      { month: 'Febbraio', monthShort: 'Feb', tempMin: 9, tempMax: 21, precipitation: 5, condition: 'sunny', conditionLabel: 'Mite', isBest: true, isWorst: false },
      { month: 'Marzo', monthShort: 'Mar', tempMin: 12, tempMax: 24, precipitation: 5, condition: 'sunny', conditionLabel: 'Piacevole', isBest: true, isWorst: false },
      { month: 'Aprile', monthShort: 'Apr', tempMin: 15, tempMax: 29, precipitation: 0, condition: 'sunny', conditionLabel: 'Caldo', isBest: true, isWorst: false },
      { month: 'Maggio', monthShort: 'Mag', tempMin: 19, tempMax: 33, precipitation: 0, condition: 'sunny', conditionLabel: 'Molto caldo', isBest: false, isWorst: false },
      { month: 'Giugno', monthShort: 'Giu', tempMin: 22, tempMax: 36, precipitation: 0, condition: 'sunny', conditionLabel: 'Estremo', isBest: false, isWorst: true, worstReason: 'Caldo estremo 36°C+' },
      { month: 'Luglio', monthShort: 'Lug', tempMin: 24, tempMax: 36, precipitation: 0, condition: 'sunny', conditionLabel: 'Estremo', isBest: false, isWorst: true, worstReason: 'Caldo estremo insopportabile' },
      { month: 'Agosto', monthShort: 'Ago', tempMin: 24, tempMax: 35, precipitation: 0, condition: 'sunny', conditionLabel: 'Estremo', isBest: false, isWorst: true, worstReason: 'Caldo estremo persistente' },
      { month: 'Settembre', monthShort: 'Set', tempMin: 22, tempMax: 33, precipitation: 0, condition: 'sunny', conditionLabel: 'Caldo', isBest: false, isWorst: false },
      { month: 'Ottobre', monthShort: 'Ott', tempMin: 18, tempMax: 30, precipitation: 0, condition: 'sunny', conditionLabel: 'Piacevole', isBest: true, isWorst: false },
      { month: 'Novembre', monthShort: 'Nov', tempMin: 14, tempMax: 25, precipitation: 0, condition: 'sunny', conditionLabel: 'Mite', isBest: true, isWorst: false },
      { month: 'Dicembre', monthShort: 'Dic', tempMin: 10, tempMax: 20, precipitation: 5, condition: 'sunny', conditionLabel: 'Fresco', isBest: true, isWorst: false },
    ],
  },
  {
    id: 'cl13',
    country: 'Messico',
    flag: '🇲🇽',
    city: 'Città del Messico',
    quickTip: 'Visita Città del Messico: novembre-aprile (secco), evita giugno-settembre (piogge giornaliere)',
    months: [
      { month: 'Gennaio', monthShort: 'Gen', tempMin: 6, tempMax: 22, precipitation: 10, condition: 'sunny', conditionLabel: 'Secco mite', isBest: true, isWorst: false },
      { month: 'Febbraio', monthShort: 'Feb', tempMin: 7, tempMax: 24, precipitation: 5, condition: 'sunny', conditionLabel: 'Secco', isBest: true, isWorst: false },
      { month: 'Marzo', monthShort: 'Mar', tempMin: 9, tempMax: 26, precipitation: 10, condition: 'sunny', conditionLabel: 'Caldo secco', isBest: true, isWorst: false },
      { month: 'Aprile', monthShort: 'Apr', tempMin: 11, tempMax: 27, precipitation: 20, condition: 'sunny', conditionLabel: 'Caldo', isBest: true, isWorst: false },
      { month: 'Maggio', monthShort: 'Mag', tempMin: 12, tempMax: 27, precipitation: 55, condition: 'partly_cloudy', conditionLabel: 'Mite', isBest: false, isWorst: false },
      { month: 'Giugno', monthShort: 'Giu', tempMin: 12, tempMax: 25, precipitation: 170, condition: 'rainy', conditionLabel: 'Piogge', isBest: false, isWorst: true, worstReason: 'Piogge giornaliere pomeridiane' },
      { month: 'Luglio', monthShort: 'Lug', tempMin: 12, tempMax: 23, precipitation: 175, condition: 'rainy', conditionLabel: 'Piogge', isBest: false, isWorst: true, worstReason: 'Piogge frequenti' },
      { month: 'Agosto', monthShort: 'Ago', tempMin: 12, tempMax: 24, precipitation: 170, condition: 'rainy', conditionLabel: 'Piogge', isBest: false, isWorst: true, worstReason: 'Piogge frequenti' },
      { month: 'Settembre', monthShort: 'Set', tempMin: 12, tempMax: 23, precipitation: 145, condition: 'rainy', conditionLabel: 'Piogge', isBest: false, isWorst: true, worstReason: 'Piogge e rischio uragani' },
      { month: 'Ottobre', monthShort: 'Ott', tempMin: 10, tempMax: 23, precipitation: 65, condition: 'partly_cloudy', conditionLabel: 'Mite', isBest: false, isWorst: false },
      { month: 'Novembre', monthShort: 'Nov', tempMin: 8, tempMax: 22, precipitation: 15, condition: 'sunny', conditionLabel: 'Secco', isBest: true, isWorst: false },
      { month: 'Dicembre', monthShort: 'Dic', tempMin: 6, tempMax: 21, precipitation: 5, condition: 'sunny', conditionLabel: 'Fresco secco', isBest: true, isWorst: false },
    ],
  },
  {
    id: 'cl14',
    country: 'Indonesia',
    flag: '🇮🇩',
    city: 'Bali',
    quickTip: 'Visita Bali: aprile-ottobre (stagione secca), evita dicembre-marzo (piogge tropicali)',
    months: [
      { month: 'Gennaio', monthShort: 'Gen', tempMin: 24, tempMax: 30, precipitation: 345, condition: 'stormy', conditionLabel: 'Piogge forti', isBest: false, isWorst: true, worstReason: 'Picco stagione piogge' },
      { month: 'Febbraio', monthShort: 'Feb', tempMin: 24, tempMax: 30, precipitation: 280, condition: 'stormy', conditionLabel: 'Piogge', isBest: false, isWorst: true, worstReason: 'Piogge intense' },
      { month: 'Marzo', monthShort: 'Mar', tempMin: 24, tempMax: 31, precipitation: 235, condition: 'rainy', conditionLabel: 'Piogge', isBest: false, isWorst: true, worstReason: 'Fine stagione piogge' },
      { month: 'Aprile', monthShort: 'Apr', tempMin: 24, tempMax: 32, precipitation: 90, condition: 'partly_cloudy', conditionLabel: 'Piacevole', isBest: true, isWorst: false },
      { month: 'Maggio', monthShort: 'Mag', tempMin: 24, tempMax: 31, precipitation: 80, condition: 'sunny', conditionLabel: 'Secco', isBest: true, isWorst: false },
      { month: 'Giugno', monthShort: 'Giu', tempMin: 23, tempMax: 30, precipitation: 55, condition: 'sunny', conditionLabel: 'Perfetto', isBest: true, isWorst: false },
      { month: 'Luglio', monthShort: 'Lug', tempMin: 23, tempMax: 30, precipitation: 50, condition: 'sunny', conditionLabel: 'Perfetto', isBest: true, isWorst: false },
      { month: 'Agosto', monthShort: 'Ago', tempMin: 23, tempMax: 30, precipitation: 25, condition: 'sunny', conditionLabel: 'Secco perfetto', isBest: true, isWorst: false },
      { month: 'Settembre', monthShort: 'Set', tempMin: 23, tempMax: 31, precipitation: 45, condition: 'sunny', conditionLabel: 'Secco', isBest: true, isWorst: false },
      { month: 'Ottobre', monthShort: 'Ott', tempMin: 24, tempMax: 31, precipitation: 65, condition: 'partly_cloudy', conditionLabel: 'Mite', isBest: true, isWorst: false },
      { month: 'Novembre', monthShort: 'Nov', tempMin: 24, tempMax: 31, precipitation: 180, condition: 'rainy', conditionLabel: 'Piogge', isBest: false, isWorst: false },
      { month: 'Dicembre', monthShort: 'Dic', tempMin: 24, tempMax: 30, precipitation: 280, condition: 'stormy', conditionLabel: 'Piogge forti', isBest: false, isWorst: true, worstReason: 'Inizio stagione piogge intense' },
    ],
  },
  {
    id: 'cl15',
    country: 'Marocco',
    flag: '🇲🇦',
    city: 'Marrakech',
    quickTip: 'Visita Marrakech: marzo-maggio e ottobre-novembre, evita luglio-agosto (caldo 45°C)',
    months: [
      { month: 'Gennaio', monthShort: 'Gen', tempMin: 6, tempMax: 18, precipitation: 30, condition: 'partly_cloudy', conditionLabel: 'Fresco', isBest: false, isWorst: false },
      { month: 'Febbraio', monthShort: 'Feb', tempMin: 8, tempMax: 20, precipitation: 30, condition: 'partly_cloudy', conditionLabel: 'Mite', isBest: false, isWorst: false },
      { month: 'Marzo', monthShort: 'Mar', tempMin: 10, tempMax: 23, precipitation: 30, condition: 'sunny', conditionLabel: 'Piacevole', isBest: true, isWorst: false },
      { month: 'Aprile', monthShort: 'Apr', tempMin: 12, tempMax: 26, precipitation: 25, condition: 'sunny', conditionLabel: 'Perfetto', isBest: true, isWorst: false },
      { month: 'Maggio', monthShort: 'Mag', tempMin: 15, tempMax: 31, precipitation: 10, condition: 'sunny', conditionLabel: 'Caldo', isBest: true, isWorst: false },
      { month: 'Giugno', monthShort: 'Giu', tempMin: 19, tempMax: 36, precipitation: 5, condition: 'sunny', conditionLabel: 'Molto caldo', isBest: false, isWorst: false },
      { month: 'Luglio', monthShort: 'Lug', tempMin: 22, tempMax: 40, precipitation: 0, condition: 'sunny', conditionLabel: 'Estremo', isBest: false, isWorst: true, worstReason: 'Caldo estremo 40°C+' },
      { month: 'Agosto', monthShort: 'Ago', tempMin: 22, tempMax: 40, precipitation: 5, condition: 'sunny', conditionLabel: 'Estremo', isBest: false, isWorst: true, worstReason: 'Caldo estremo insopportabile' },
      { month: 'Settembre', monthShort: 'Set', tempMin: 19, tempMax: 34, precipitation: 10, condition: 'sunny', conditionLabel: 'Caldo', isBest: false, isWorst: false },
      { month: 'Ottobre', monthShort: 'Ott', tempMin: 14, tempMax: 28, precipitation: 20, condition: 'sunny', conditionLabel: 'Piacevole', isBest: true, isWorst: false },
      { month: 'Novembre', monthShort: 'Nov', tempMin: 10, tempMax: 22, precipitation: 30, condition: 'partly_cloudy', conditionLabel: 'Mite', isBest: true, isWorst: false },
      { month: 'Dicembre', monthShort: 'Dic', tempMin: 7, tempMax: 19, precipitation: 25, condition: 'partly_cloudy', conditionLabel: 'Fresco', isBest: false, isWorst: false },
    ],
  },
  {
    id: 'cl16',
    country: 'Argentina',
    flag: '🇦🇷',
    city: 'Buenos Aires',
    quickTip: 'Visita Buenos Aires: marzo-maggio e settembre-novembre, evita gennaio (afa) e luglio (freddo)',
    months: [
      { month: 'Gennaio', monthShort: 'Gen', tempMin: 20, tempMax: 31, precipitation: 120, condition: 'humid', conditionLabel: 'Afoso', isBest: false, isWorst: true, worstReason: 'Afa estrema e umidità' },
      { month: 'Febbraio', monthShort: 'Feb', tempMin: 20, tempMax: 30, precipitation: 115, condition: 'humid', conditionLabel: 'Afoso', isBest: false, isWorst: false },
      { month: 'Marzo', monthShort: 'Mar', tempMin: 17, tempMax: 27, precipitation: 110, condition: 'partly_cloudy', conditionLabel: 'Piacevole', isBest: true, isWorst: false },
      { month: 'Aprile', monthShort: 'Apr', tempMin: 13, tempMax: 23, precipitation: 85, condition: 'partly_cloudy', conditionLabel: 'Mite', isBest: true, isWorst: false },
      { month: 'Maggio', monthShort: 'Mag', tempMin: 10, tempMax: 19, precipitation: 70, condition: 'partly_cloudy', conditionLabel: 'Fresco', isBest: true, isWorst: false },
      { month: 'Giugno', monthShort: 'Giu', tempMin: 7, tempMax: 16, precipitation: 50, condition: 'cloudy', conditionLabel: 'Freddo', isBest: false, isWorst: false },
      { month: 'Luglio', monthShort: 'Lug', tempMin: 7, tempMax: 15, precipitation: 50, condition: 'cloudy', conditionLabel: 'Freddo', isBest: false, isWorst: true, worstReason: 'Freddo e grigio' },
      { month: 'Agosto', monthShort: 'Ago', tempMin: 8, tempMax: 17, precipitation: 55, condition: 'cloudy', conditionLabel: 'Fresco', isBest: false, isWorst: false },
      { month: 'Settembre', monthShort: 'Set', tempMin: 10, tempMax: 19, precipitation: 70, condition: 'partly_cloudy', conditionLabel: 'Mite', isBest: true, isWorst: false },
      { month: 'Ottobre', monthShort: 'Ott', tempMin: 13, tempMax: 23, precipitation: 105, condition: 'partly_cloudy', conditionLabel: 'Piacevole', isBest: true, isWorst: false },
      { month: 'Novembre', monthShort: 'Nov', tempMin: 16, tempMax: 26, precipitation: 95, condition: 'sunny', conditionLabel: 'Caldo', isBest: true, isWorst: false },
      { month: 'Dicembre', monthShort: 'Dic', tempMin: 19, tempMax: 29, precipitation: 95, condition: 'sunny', conditionLabel: 'Caldo', isBest: false, isWorst: false },
    ],
  },
  {
    id: 'cl17',
    country: 'Sudafrica',
    flag: '🇿🇦',
    city: 'Città del Capo',
    quickTip: 'Visita Città del Capo: novembre-marzo (estate australe), evita giugno-agosto (inverno piovoso)',
    months: [
      { month: 'Gennaio', monthShort: 'Gen', tempMin: 16, tempMax: 27, precipitation: 15, condition: 'sunny', conditionLabel: 'Estate', isBest: true, isWorst: false },
      { month: 'Febbraio', monthShort: 'Feb', tempMin: 16, tempMax: 28, precipitation: 15, condition: 'sunny', conditionLabel: 'Estate', isBest: true, isWorst: false },
      { month: 'Marzo', monthShort: 'Mar', tempMin: 14, tempMax: 26, precipitation: 20, condition: 'sunny', conditionLabel: 'Caldo', isBest: true, isWorst: false },
      { month: 'Aprile', monthShort: 'Apr', tempMin: 12, tempMax: 23, precipitation: 40, condition: 'partly_cloudy', conditionLabel: 'Mite', isBest: false, isWorst: false },
      { month: 'Maggio', monthShort: 'Mag', tempMin: 10, tempMax: 20, precipitation: 70, condition: 'rainy', conditionLabel: 'Piogge', isBest: false, isWorst: false },
      { month: 'Giugno', monthShort: 'Giu', tempMin: 8, tempMax: 18, precipitation: 90, condition: 'rainy', conditionLabel: 'Inverno piovoso', isBest: false, isWorst: true, worstReason: 'Inverno piovoso e freddo' },
      { month: 'Luglio', monthShort: 'Lug', tempMin: 7, tempMax: 17, precipitation: 85, condition: 'rainy', conditionLabel: 'Inverno', isBest: false, isWorst: true, worstReason: 'Piogge frequenti e freddo' },
      { month: 'Agosto', monthShort: 'Ago', tempMin: 8, tempMax: 18, precipitation: 75, condition: 'rainy', conditionLabel: 'Fresco', isBest: false, isWorst: true, worstReason: 'Ancora piovoso' },
      { month: 'Settembre', monthShort: 'Set', tempMin: 9, tempMax: 19, precipitation: 45, condition: 'partly_cloudy', conditionLabel: 'Mite', isBest: false, isWorst: false },
      { month: 'Ottobre', monthShort: 'Ott', tempMin: 11, tempMax: 22, precipitation: 30, condition: 'sunny', conditionLabel: 'Primavera', isBest: false, isWorst: false },
      { month: 'Novembre', monthShort: 'Nov', tempMin: 13, tempMax: 24, precipitation: 20, condition: 'sunny', conditionLabel: 'Piacevole', isBest: true, isWorst: false },
      { month: 'Dicembre', monthShort: 'Dic', tempMin: 15, tempMax: 26, precipitation: 15, condition: 'sunny', conditionLabel: 'Estate', isBest: true, isWorst: false },
    ],
  },
  {
    id: 'cl18',
    country: 'Portogallo',
    flag: '🇵🇹',
    city: 'Lisbona',
    quickTip: 'Visita Lisbona: aprile-ottobre (sole), evita novembre-febbraio (piogge e fresco)',
    months: [
      { month: 'Gennaio', monthShort: 'Gen', tempMin: 8, tempMax: 15, precipitation: 95, condition: 'rainy', conditionLabel: 'Piogge', isBest: false, isWorst: true, worstReason: 'Piogge frequenti' },
      { month: 'Febbraio', monthShort: 'Feb', tempMin: 9, tempMax: 16, precipitation: 85, condition: 'rainy', conditionLabel: 'Piogge', isBest: false, isWorst: true, worstReason: 'Piogge frequenti' },
      { month: 'Marzo', monthShort: 'Mar', tempMin: 10, tempMax: 18, precipitation: 55, condition: 'partly_cloudy', conditionLabel: 'Mite', isBest: false, isWorst: false },
      { month: 'Aprile', monthShort: 'Apr', tempMin: 12, tempMax: 20, precipitation: 55, condition: 'partly_cloudy', conditionLabel: 'Piacevole', isBest: true, isWorst: false },
      { month: 'Maggio', monthShort: 'Mag', tempMin: 14, tempMax: 23, precipitation: 40, condition: 'sunny', conditionLabel: 'Soleggiato', isBest: true, isWorst: false },
      { month: 'Giugno', monthShort: 'Giu', tempMin: 17, tempMax: 27, precipitation: 15, condition: 'sunny', conditionLabel: 'Caldo', isBest: true, isWorst: false },
      { month: 'Luglio', monthShort: 'Lug', tempMin: 19, tempMax: 30, precipitation: 5, condition: 'sunny', conditionLabel: 'Molto caldo', isBest: true, isWorst: false },
      { month: 'Agosto', monthShort: 'Ago', tempMin: 19, tempMax: 30, precipitation: 5, condition: 'sunny', conditionLabel: 'Caldo', isBest: true, isWorst: false },
      { month: 'Settembre', monthShort: 'Set', tempMin: 17, tempMax: 28, precipitation: 25, condition: 'sunny', conditionLabel: 'Piacevole', isBest: true, isWorst: false },
      { month: 'Ottobre', monthShort: 'Ott', tempMin: 14, tempMax: 23, precipitation: 75, condition: 'partly_cloudy', conditionLabel: 'Mite', isBest: true, isWorst: false },
      { month: 'Novembre', monthShort: 'Nov', tempMin: 11, tempMax: 18, precipitation: 105, condition: 'rainy', conditionLabel: 'Piogge', isBest: false, isWorst: false },
      { month: 'Dicembre', monthShort: 'Dic', tempMin: 9, tempMax: 15, precipitation: 105, condition: 'rainy', conditionLabel: 'Piogge', isBest: false, isWorst: false },
    ],
  },
  {
    id: 'cl19',
    country: 'Grecia',
    flag: '🇬🇷',
    city: 'Atene',
    quickTip: 'Visita Atene: aprile-giugno e settembre-ottobre, evita luglio-agosto (caldo 40°C e folla)',
    months: [
      { month: 'Gennaio', monthShort: 'Gen', tempMin: 6, tempMax: 13, precipitation: 55, condition: 'rainy', conditionLabel: 'Piogge', isBest: false, isWorst: false },
      { month: 'Febbraio', monthShort: 'Feb', tempMin: 7, tempMax: 14, precipitation: 45, condition: 'partly_cloudy', conditionLabel: 'Fresco', isBest: false, isWorst: false },
      { month: 'Marzo', monthShort: 'Mar', tempMin: 8, tempMax: 16, precipitation: 40, condition: 'partly_cloudy', conditionLabel: 'Mite', isBest: false, isWorst: false },
      { month: 'Aprile', monthShort: 'Apr', tempMin: 11, tempMax: 20, precipitation: 30, condition: 'sunny', conditionLabel: 'Piacevole', isBest: true, isWorst: false },
      { month: 'Maggio', monthShort: 'Mag', tempMin: 15, tempMax: 26, precipitation: 15, condition: 'sunny', conditionLabel: 'Perfetto', isBest: true, isWorst: false },
      { month: 'Giugno', monthShort: 'Giu', tempMin: 20, tempMax: 31, precipitation: 5, condition: 'sunny', conditionLabel: 'Caldo', isBest: true, isWorst: false },
      { month: 'Luglio', monthShort: 'Lug', tempMin: 23, tempMax: 34, precipitation: 5, condition: 'sunny', conditionLabel: 'Molto caldo', isBest: false, isWorst: true, worstReason: 'Caldo estremo e folla turistica' },
      { month: 'Agosto', monthShort: 'Ago', tempMin: 23, tempMax: 34, precipitation: 5, condition: 'sunny', conditionLabel: 'Molto caldo', isBest: false, isWorst: true, worstReason: 'Caldo estremo e folla' },
      { month: 'Settembre', monthShort: 'Set', tempMin: 19, tempMax: 30, precipitation: 15, condition: 'sunny', conditionLabel: 'Piacevole', isBest: true, isWorst: false },
      { month: 'Ottobre', monthShort: 'Ott', tempMin: 15, tempMax: 24, precipitation: 45, condition: 'partly_cloudy', conditionLabel: 'Mite', isBest: true, isWorst: false },
      { month: 'Novembre', monthShort: 'Nov', tempMin: 11, tempMax: 19, precipitation: 55, condition: 'rainy', conditionLabel: 'Piogge', isBest: false, isWorst: false },
      { month: 'Dicembre', monthShort: 'Dic', tempMin: 8, tempMax: 15, precipitation: 65, condition: 'rainy', conditionLabel: 'Piogge', isBest: false, isWorst: false },
    ],
  },
  {
    id: 'cl20',
    country: 'Islanda',
    flag: '🇮🇸',
    city: 'Reykjavik',
    quickTip: 'Visita Islanda: giugno-agosto (sole 24h), settembre-marzo per aurora boreale, evita novembre-gennaio (buio totale)',
    months: [
      { month: 'Gennaio', monthShort: 'Gen', tempMin: -3, tempMax: 2, precipitation: 75, condition: 'snowy', conditionLabel: 'Neve e buio', isBest: false, isWorst: true, worstReason: 'Solo 4-5 ore di luce' },
      { month: 'Febbraio', monthShort: 'Feb', tempMin: -2, tempMax: 3, precipitation: 70, condition: 'snowy', conditionLabel: 'Neve', isBest: false, isWorst: false },
      { month: 'Marzo', monthShort: 'Mar', tempMin: -1, tempMax: 4, precipitation: 65, condition: 'snowy', conditionLabel: 'Aurora + neve', isBest: false, isWorst: false },
      { month: 'Aprile', monthShort: 'Apr', tempMin: 1, tempMax: 7, precipitation: 50, condition: 'cloudy', conditionLabel: 'Fresco', isBest: false, isWorst: false },
      { month: 'Maggio', monthShort: 'Mag', tempMin: 4, tempMax: 10, precipitation: 45, condition: 'partly_cloudy', conditionLabel: 'Mite', isBest: false, isWorst: false },
      { month: 'Giugno', monthShort: 'Giu', tempMin: 7, tempMax: 13, precipitation: 50, condition: 'partly_cloudy', conditionLabel: 'Sole 24h', isBest: true, isWorst: false },
      { month: 'Luglio', monthShort: 'Lug', tempMin: 9, tempMax: 14, precipitation: 50, condition: 'partly_cloudy', conditionLabel: 'Estate', isBest: true, isWorst: false },
      { month: 'Agosto', monthShort: 'Ago', tempMin: 8, tempMax: 14, precipitation: 60, condition: 'partly_cloudy', conditionLabel: 'Estate', isBest: true, isWorst: false },
      { month: 'Settembre', monthShort: 'Set', tempMin: 5, tempMax: 11, precipitation: 65, condition: 'cloudy', conditionLabel: 'Aurora boreale', isBest: false, isWorst: false },
      { month: 'Ottobre', monthShort: 'Ott', tempMin: 2, tempMax: 7, precipitation: 80, condition: 'rainy', conditionLabel: 'Aurora + pioggia', isBest: false, isWorst: false },
      { month: 'Novembre', monthShort: 'Nov', tempMin: -1, tempMax: 4, precipitation: 70, condition: 'snowy', conditionLabel: 'Neve e buio', isBest: false, isWorst: true, worstReason: 'Buio quasi totale e freddo' },
      { month: 'Dicembre', monthShort: 'Dic', tempMin: -2, tempMax: 3, precipitation: 75, condition: 'snowy', conditionLabel: 'Neve e buio', isBest: false, isWorst: true, worstReason: 'Solo 3-4 ore di luce' },
    ],
  },
];
