export interface HealthInfo {
  country: string;
  flag: string;
  vaccines: { name: string; required: boolean; notes: string }[];
  medicines: string[];
  emergencyNumber: string;
  tips: string[];
}

export const healthByCountry: HealthInfo[] = [
  {
    country: 'Thailandia',
    flag: '🇹🇭',
    vaccines: [
      { name: 'Epatite A', required: true, notes: 'Consigliato per tutti i viaggiatori' },
      { name: 'Epatite B', required: false, notes: 'Per soggiorni prolungati' },
      { name: 'Febbre Tifoide', required: false, notes: 'Se si mangiano cibi di strada' },
      { name: 'Encefalite Giapponese', required: false, notes: 'Per zone rurali e soggiorni >1 mese' },
      { name: 'Rabbia', required: false, notes: 'Se a contatto con animali' },
    ],
    medicines: ['Antimalarici (zone rurali)', 'Repellente DEET 30%+', 'Reidratazione orale', 'Antidiarroici', 'Protezione solare SPF50+'],
    emergencyNumber: '1669',
    tips: ['Bevi solo acqua in bottiglia sigillata', 'Attenzione al ghiaccio nelle bevande', 'Usa repellente per zanzare al tramonto'],
  },
  {
    country: 'Brasile',
    flag: '🇧🇷',
    vaccines: [
      { name: 'Febbre Gialla', required: true, notes: 'Obbligatorio per alcune regioni' },
      { name: 'Epatite A', required: true, notes: 'Consigliato per tutti' },
      { name: 'Epatite B', required: false, notes: 'Per soggiorni prolungati' },
      { name: 'Febbre Tifoide', required: false, notes: 'Per zone rurali' },
      { name: 'Rabbia', required: false, notes: 'Se si visitano zone forestali' },
    ],
    medicines: ['Antimalarici (Amazzonia)', 'Repellente DEET 30%+', 'Protezione solare SPF50+', 'Antidiarroici', 'Kit pronto soccorso'],
    emergencyNumber: '192',
    tips: ['Vaccino febbre gialla almeno 10 giorni prima', 'Protezione zanzare h24 in Amazzonia', 'Evita acqua del rubinetto'],
  },
  {
    country: 'India',
    flag: '🇮🇳',
    vaccines: [
      { name: 'Epatite A', required: true, notes: 'Fondamentale per tutti' },
      { name: 'Epatite B', required: true, notes: 'Consigliato per tutti' },
      { name: 'Febbre Tifoide', required: true, notes: 'Altamente consigliato' },
      { name: 'Colera', required: false, notes: 'Per zone ad alto rischio' },
      { name: 'Encefalite Giapponese', required: false, notes: 'Per zone rurali' },
      { name: 'Rabbia', required: false, notes: 'Per soggiorni prolungati' },
    ],
    medicines: ['Antimalarici', 'Reidratazione orale', 'Antidiarroici (Loperamide)', 'Antibiotico ad ampio spettro', 'Repellente DEET 50%'],
    emergencyNumber: '112',
    tips: ['Mai bere acqua del rubinetto', 'Evita ghiaccio e insalate crude', 'Lava spesso le mani con disinfettante'],
  },
  {
    country: 'Kenya',
    flag: '🇰🇪',
    vaccines: [
      { name: 'Febbre Gialla', required: true, notes: 'Certificato obbligatorio' },
      { name: 'Epatite A', required: true, notes: 'Consigliato per tutti' },
      { name: 'Epatite B', required: true, notes: 'Consigliato per tutti' },
      { name: 'Febbre Tifoide', required: true, notes: 'Altamente consigliato' },
      { name: 'Meningite', required: false, notes: 'Per stagione secca' },
      { name: 'Rabbia', required: false, notes: 'Per safari e zone rurali' },
    ],
    medicines: ['Antimalarici (Malarone/Lariam)', 'Repellente DEET 50%', 'Rete antizanzare', 'Reidratazione orale', 'Antibiotico emergenza'],
    emergencyNumber: '999',
    tips: ['Profilassi antimalarica obbligatoria', 'Dormi sotto zanzariera trattata', 'Indossa maniche lunghe dopo il tramonto'],
  },
  {
    country: 'Giappone',
    flag: '🇯🇵',
    vaccines: [
      { name: 'Encefalite Giapponese', required: false, notes: 'Solo per zone rurali in estate' },
      { name: 'Epatite A', required: false, notes: 'Per precauzione' },
      { name: 'Epatite B', required: false, notes: 'Per soggiorni prolungati' },
    ],
    medicines: ['Antistaminici (allergie stagionali)', 'Cerotti per vesciche', 'Protezione solare', 'Farmaci personali con prescrizione'],
    emergencyNumber: '119',
    tips: ['Paese molto sicuro dal punto di vista sanitario', 'Farmacie ovunque ma pochi parlano inglese', 'Porta prescrizione medica per farmaci personali'],
  },
  {
    country: 'Messico',
    flag: '🇲🇽',
    vaccines: [
      { name: 'Epatite A', required: true, notes: 'Consigliato per tutti' },
      { name: 'Epatite B', required: false, notes: 'Per soggiorni prolungati' },
      { name: 'Febbre Tifoide', required: false, notes: 'Per zone rurali' },
      { name: 'Rabbia', required: false, notes: 'Se a contatto con animali' },
    ],
    medicines: ['Antidiarroici', 'Reidratazione orale', 'Repellente per zanzare', 'Protezione solare SPF50+', 'Antistaminici'],
    emergencyNumber: '911',
    tips: ['Evita acqua del rubinetto', 'Lava frutta e verdura con acqua purificata', 'Attenzione alle zanzare (Dengue)'],
  },
  {
    country: 'Egitto',
    flag: '🇪🇬',
    vaccines: [
      { name: 'Epatite A', required: true, notes: 'Consigliato per tutti' },
      { name: 'Epatite B', required: false, notes: 'Per soggiorni prolungati' },
      { name: 'Febbre Tifoide', required: false, notes: 'Per zone rurali' },
      { name: 'Rabbia', required: false, notes: 'Se a contatto con animali randagi' },
    ],
    medicines: ['Antidiarroici', 'Reidratazione orale', 'Protezione solare SPF50+', 'Collirio per polvere/sabbia', 'Disinfettante mani'],
    emergencyNumber: '123',
    tips: ['Bevi solo acqua in bottiglia', 'Evita cibi crudi nei mercati', 'Proteggiti dal sole nelle ore centrali'],
  },
  {
    country: 'Stati Uniti',
    flag: '🇺🇸',
    vaccines: [
      { name: 'Nessun vaccino obbligatorio', required: false, notes: 'Verifica copertura vaccinale standard' },
    ],
    medicines: ['Farmaci personali con prescrizione', 'Antistaminici', 'Protezione solare'],
    emergencyNumber: '911',
    tips: ['Assicurazione sanitaria INDISPENSABILE', 'Costi sanitari molto elevati', 'Porta prescrizioni mediche originali'],
  },
  {
    country: 'Spagna',
    flag: '🇪🇸',
    vaccines: [
      { name: 'Nessun vaccino obbligatorio', required: false, notes: 'Tessera sanitaria europea valida' },
    ],
    medicines: ['Protezione solare SPF50+', 'Farmaci personali', 'Cerotti e disinfettante'],
    emergencyNumber: '112',
    tips: ['Tessera sanitaria europea (TEAM) valida', 'Farmacie con croce verde ovunque', 'Attenzione ai colpi di calore in estate'],
  },
  {
    country: 'Australia',
    flag: '🇦🇺',
    vaccines: [
      { name: 'Epatite B', required: false, notes: 'Per soggiorni prolungati' },
      { name: 'Encefalite Giapponese', required: false, notes: 'Per zone tropicali del nord' },
    ],
    medicines: ['Protezione solare SPF50+', 'Repellente insetti', 'Antistaminici', 'Kit morsi/punture'],
    emergencyNumber: '000',
    tips: ['Protezione solare obbligatoria (buco ozono)', 'Attenzione fauna marina pericolosa', 'Assicurazione sanitaria consigliata'],
  },
  {
    country: 'Francia',
    flag: '🇫🇷',
    vaccines: [
      { name: 'Nessun vaccino obbligatorio', required: false, notes: 'Tessera sanitaria europea valida' },
    ],
    medicines: ['Farmaci personali', 'Protezione solare', 'Cerotti e disinfettante'],
    emergencyNumber: '15',
    tips: ['Tessera sanitaria europea (TEAM) valida', 'Farmacie ovunque con croce verde', 'Sistema sanitario eccellente'],
  },
  {
    country: 'Germania',
    flag: '🇩🇪',
    vaccines: [
      { name: 'Encefalite da zecche (TBE)', required: false, notes: 'Per zone rurali della Baviera e Baden-Württemberg' },
    ],
    medicines: ['Farmaci personali', 'Repellente antizecche', 'Cerotti e disinfettante'],
    emergencyNumber: '112',
    tips: ['Tessera sanitaria europea (TEAM) valida', 'Farmacie (Apotheke) ovunque', 'Attenzione alle zecche in zone boschive'],
  },
  {
    country: 'Regno Unito',
    flag: '🇬🇧',
    vaccines: [
      { name: 'Nessun vaccino obbligatorio', required: false, notes: 'Verifica copertura vaccinale standard' },
    ],
    medicines: ['Farmaci personali', 'Antistaminici per allergie', 'Protezione solare estiva'],
    emergencyNumber: '999',
    tips: ['NHS gratuito per emergenze', 'Farmacie (Pharmacy/Chemist) ovunque', 'TEAM non più valida post-Brexit, consigliata assicurazione'],
  },
  {
    country: 'Portogallo',
    flag: '🇵🇹',
    vaccines: [
      { name: 'Nessun vaccino obbligatorio', required: false, notes: 'Tessera sanitaria europea valida' },
    ],
    medicines: ['Protezione solare SPF50+', 'Farmaci personali', 'Repellente per zanzare (estate)'],
    emergencyNumber: '112',
    tips: ['Tessera sanitaria europea (TEAM) valida', 'Farmacie ben fornite', 'Attenzione al sole estivo, molto forte'],
  },
  {
    country: 'Grecia',
    flag: '🇬🇷',
    vaccines: [
      { name: 'Nessun vaccino obbligatorio', required: false, notes: 'Tessera sanitaria europea valida' },
    ],
    medicines: ['Protezione solare SPF50+', 'Repellente per zanzare', 'Reidratazione orale', 'Farmaci personali'],
    emergencyNumber: '166',
    tips: ['Tessera sanitaria europea (TEAM) valida', 'Attenzione ai colpi di calore', 'Bevi molta acqua nelle isole'],
  },
  {
    country: 'Turchia',
    flag: '🇹🇷',
    vaccines: [
      { name: 'Epatite A', required: false, notes: 'Consigliato per zone rurali' },
      { name: 'Epatite B', required: false, notes: 'Per soggiorni prolungati' },
    ],
    medicines: ['Antidiarroici', 'Protezione solare SPF50+', 'Repellente insetti', 'Farmaci personali'],
    emergencyNumber: '112',
    tips: ['Acqua del rubinetto sconsigliata in molte zone', 'Assicurazione sanitaria consigliata', 'Ospedali privati eccellenti nelle grandi città'],
  },
  {
    country: 'Marocco',
    flag: '🇲🇦',
    vaccines: [
      { name: 'Epatite A', required: true, notes: 'Consigliato per tutti' },
      { name: 'Epatite B', required: false, notes: 'Per soggiorni prolungati' },
      { name: 'Febbre Tifoide', required: false, notes: 'Per zone rurali' },
      { name: 'Rabbia', required: false, notes: 'Se a contatto con animali randagi' },
    ],
    medicines: ['Antidiarroici', 'Reidratazione orale', 'Protezione solare SPF50+', 'Disinfettante mani', 'Repellente insetti'],
    emergencyNumber: '15',
    tips: ['Evita acqua del rubinetto', 'Attenzione ai cibi crudi nei souk', 'Porta disinfettante per le mani'],
  },
  {
    country: 'Tunisia',
    flag: '🇹🇳',
    vaccines: [
      { name: 'Epatite A', required: true, notes: 'Consigliato per tutti' },
      { name: 'Epatite B', required: false, notes: 'Per soggiorni prolungati' },
      { name: 'Rabbia', required: false, notes: 'Se a contatto con animali' },
    ],
    medicines: ['Antidiarroici', 'Reidratazione orale', 'Protezione solare SPF50+', 'Disinfettante mani'],
    emergencyNumber: '190',
    tips: ['Evita acqua del rubinetto', 'Proteggiti dal sole nel deserto', 'Assicurazione sanitaria consigliata'],
  },
  {
    country: 'Sudafrica',
    flag: '🇿🇦',
    vaccines: [
      { name: 'Febbre Gialla', required: false, notes: 'Obbligatorio se arrivi da paese endemico' },
      { name: 'Epatite A', required: true, notes: 'Consigliato per tutti' },
      { name: 'Epatite B', required: true, notes: 'Consigliato per tutti' },
      { name: 'Febbre Tifoide', required: false, notes: 'Per zone rurali' },
      { name: 'Rabbia', required: false, notes: 'Per safari e zone rurali' },
    ],
    medicines: ['Antimalarici (Kruger Park)', 'Repellente DEET 50%', 'Protezione solare SPF50+', 'Kit pronto soccorso'],
    emergencyNumber: '10177',
    tips: ['Profilassi antimalarica per zone a rischio', 'Non bere acqua del rubinetto fuori dalle città', 'Assicurazione sanitaria obbligatoria'],
  },
  {
    country: 'Tanzania',
    flag: '🇹🇿',
    vaccines: [
      { name: 'Febbre Gialla', required: true, notes: 'Certificato obbligatorio' },
      { name: 'Epatite A', required: true, notes: 'Consigliato per tutti' },
      { name: 'Epatite B', required: true, notes: 'Consigliato per tutti' },
      { name: 'Febbre Tifoide', required: true, notes: 'Altamente consigliato' },
      { name: 'Rabbia', required: false, notes: 'Per safari e zone rurali' },
      { name: 'Colera', required: false, notes: 'Per zone ad alto rischio' },
    ],
    medicines: ['Antimalarici obbligatori', 'Repellente DEET 50%', 'Rete antizanzare', 'Reidratazione orale', 'Antibiotico emergenza'],
    emergencyNumber: '114',
    tips: ['Profilassi antimalarica obbligatoria', 'Solo acqua in bottiglia', 'Protezione totale dalle zanzare'],
  },
  {
    country: 'Nigeria',
    flag: '🇳🇬',
    vaccines: [
      { name: 'Febbre Gialla', required: true, notes: 'Certificato obbligatorio' },
      { name: 'Epatite A', required: true, notes: 'Consigliato per tutti' },
      { name: 'Epatite B', required: true, notes: 'Consigliato per tutti' },
      { name: 'Febbre Tifoide', required: true, notes: 'Altamente consigliato' },
      { name: 'Meningite', required: true, notes: 'Per la stagione secca nel nord' },
      { name: 'Rabbia', required: false, notes: 'Per zone rurali' },
    ],
    medicines: ['Antimalarici obbligatori', 'Repellente DEET 50%', 'Reidratazione orale', 'Antibiotico ad ampio spettro', 'Kit pronto soccorso'],
    emergencyNumber: '199',
    tips: ['Profilassi antimalarica obbligatoria', 'Solo acqua in bottiglia sigillata', 'Assicurazione sanitaria completa indispensabile'],
  },
  {
    country: 'Etiopia',
    flag: '🇪🇹',
    vaccines: [
      { name: 'Febbre Gialla', required: true, notes: 'Certificato obbligatorio' },
      { name: 'Epatite A', required: true, notes: 'Consigliato per tutti' },
      { name: 'Epatite B', required: true, notes: 'Consigliato per tutti' },
      { name: 'Febbre Tifoide', required: true, notes: 'Altamente consigliato' },
      { name: 'Meningite', required: false, notes: 'Per la stagione secca' },
      { name: 'Rabbia', required: false, notes: 'Per zone rurali' },
    ],
    medicines: ['Antimalarici', 'Repellente DEET 50%', 'Reidratazione orale', 'Antibiotico emergenza', 'Medicine per altitudine (Diamox)'],
    emergencyNumber: '907',
    tips: ['Profilassi antimalarica per zone sotto 2000m', 'Attenzione al mal di montagna (altopiani)', 'Solo acqua in bottiglia'],
  },
  {
    country: 'Vietnam',
    flag: '🇻🇳',
    vaccines: [
      { name: 'Epatite A', required: true, notes: 'Consigliato per tutti' },
      { name: 'Epatite B', required: false, notes: 'Per soggiorni prolungati' },
      { name: 'Febbre Tifoide', required: false, notes: 'Per zone rurali' },
      { name: 'Encefalite Giapponese', required: false, notes: 'Per zone rurali e risaie' },
      { name: 'Rabbia', required: false, notes: 'Se a contatto con animali' },
    ],
    medicines: ['Repellente DEET 30%+', 'Antidiarroici', 'Reidratazione orale', 'Protezione solare SPF50+', 'Disinfettante mani'],
    emergencyNumber: '115',
    tips: ['Evita acqua del rubinetto', 'Attenzione al cibo di strada (scegli bancarelle affollate)', 'Repellente zanzare essenziale'],
  },
  {
    country: 'Indonesia',
    flag: '🇮🇩',
    vaccines: [
      { name: 'Epatite A', required: true, notes: 'Consigliato per tutti' },
      { name: 'Epatite B', required: false, notes: 'Per soggiorni prolungati' },
      { name: 'Febbre Tifoide', required: false, notes: 'Per zone rurali' },
      { name: 'Rabbia', required: false, notes: 'Molto presente, attenzione ai cani e scimmie' },
      { name: 'Encefalite Giapponese', required: false, notes: 'Per zone rurali' },
    ],
    medicines: ['Antimalarici (fuori Bali/Java)', 'Repellente DEET 30%+', 'Antidiarroici', 'Protezione solare SPF50+', 'Kit pronto soccorso'],
    emergencyNumber: '118',
    tips: ['Evita acqua del rubinetto', 'Attenzione alle scimmie (rabbia)', 'Repellente zanzare essenziale (Dengue)'],
  },
  {
    country: 'Cambogia',
    flag: '🇰🇭',
    vaccines: [
      { name: 'Epatite A', required: true, notes: 'Consigliato per tutti' },
      { name: 'Epatite B', required: true, notes: 'Consigliato per tutti' },
      { name: 'Febbre Tifoide', required: false, notes: 'Per zone rurali' },
      { name: 'Rabbia', required: false, notes: 'Per zone rurali' },
      { name: 'Encefalite Giapponese', required: false, notes: 'Per zone rurali' },
    ],
    medicines: ['Antimalarici (zone rurali)', 'Repellente DEET 30%+', 'Antidiarroici', 'Reidratazione orale', 'Kit pronto soccorso'],
    emergencyNumber: '119',
    tips: ['Solo acqua in bottiglia', 'Assicurazione con evacuazione medica consigliata', 'Ospedali limitati fuori Phnom Penh'],
  },
  {
    country: 'Nepal',
    flag: '🇳🇵',
    vaccines: [
      { name: 'Epatite A', required: true, notes: 'Consigliato per tutti' },
      { name: 'Epatite B', required: true, notes: 'Consigliato per tutti' },
      { name: 'Febbre Tifoide', required: true, notes: 'Altamente consigliato' },
      { name: 'Rabbia', required: false, notes: 'Per trekking e zone rurali' },
      { name: 'Encefalite Giapponese', required: false, notes: 'Per Terai in estate' },
    ],
    medicines: ['Medicine per altitudine (Diamox)', 'Antimalarici (Terai)', 'Reidratazione orale', 'Antibiotico emergenza', 'Purificatore acqua'],
    emergencyNumber: '102',
    tips: ['Attenzione al mal di montagna sopra 3000m', 'Solo acqua purificata', 'Assicurazione con evacuazione elicottero per trekking'],
  },
  {
    country: 'Sri Lanka',
    flag: '🇱🇰',
    vaccines: [
      { name: 'Epatite A', required: true, notes: 'Consigliato per tutti' },
      { name: 'Epatite B', required: false, notes: 'Per soggiorni prolungati' },
      { name: 'Febbre Tifoide', required: false, notes: 'Per zone rurali' },
      { name: 'Rabbia', required: false, notes: 'Attenzione ai cani randagi' },
    ],
    medicines: ['Repellente DEET 30%+', 'Antidiarroici', 'Protezione solare SPF50+', 'Reidratazione orale', 'Disinfettante mani'],
    emergencyNumber: '110',
    tips: ['Evita acqua del rubinetto', 'Protezione solare indispensabile', 'Attenzione ai cani randagi'],
  },
  {
    country: 'Filippine',
    flag: '🇵🇭',
    vaccines: [
      { name: 'Epatite A', required: true, notes: 'Consigliato per tutti' },
      { name: 'Epatite B', required: false, notes: 'Per soggiorni prolungati' },
      { name: 'Febbre Tifoide', required: false, notes: 'Per zone rurali' },
      { name: 'Rabbia', required: false, notes: 'Per zone rurali' },
    ],
    medicines: ['Repellente DEET 30%+', 'Antidiarroici', 'Protezione solare SPF50+', 'Kit pronto soccorso', 'Reidratazione orale'],
    emergencyNumber: '911',
    tips: ['Evita acqua del rubinetto', 'Repellente zanzare essenziale (Dengue)', 'Assicurazione sanitaria consigliata'],
  },
  {
    country: 'Cina',
    flag: '🇨🇳',
    vaccines: [
      { name: 'Epatite A', required: true, notes: 'Consigliato per tutti' },
      { name: 'Epatite B', required: false, notes: 'Per soggiorni prolungati' },
      { name: 'Febbre Tifoide', required: false, notes: 'Per zone rurali' },
      { name: 'Encefalite Giapponese', required: false, notes: 'Per zone rurali in estate' },
      { name: 'Rabbia', required: false, notes: 'Per zone rurali' },
    ],
    medicines: ['Antidiarroici', 'Reidratazione orale', 'Disinfettante mani', 'Mascherine FFP2', 'Farmaci personali con prescrizione'],
    emergencyNumber: '120',
    tips: ['Acqua del rubinetto non potabile', 'Porta farmaci con prescrizione tradotta in cinese', 'Inquinamento: porta mascherine nelle grandi città'],
  },
  {
    country: 'Corea del Sud',
    flag: '🇰🇷',
    vaccines: [
      { name: 'Epatite A', required: false, notes: 'Per precauzione' },
      { name: 'Epatite B', required: false, notes: 'Per soggiorni prolungati' },
      { name: 'Encefalite Giapponese', required: false, notes: 'Per zone rurali in estate' },
    ],
    medicines: ['Antistaminici', 'Farmaci personali', 'Protezione solare', 'Cerotti e disinfettante'],
    emergencyNumber: '119',
    tips: ['Paese molto sicuro sanitariamente', 'Farmacie ovunque', 'Sistema sanitario eccellente'],
  },
  {
    country: 'Canada',
    flag: '🇨🇦',
    vaccines: [
      { name: 'Nessun vaccino obbligatorio', required: false, notes: 'Verifica copertura vaccinale standard' },
    ],
    medicines: ['Farmaci personali con prescrizione', 'Protezione solare', 'Repellente insetti (estate)'],
    emergencyNumber: '911',
    tips: ['Assicurazione sanitaria necessaria', 'Costi sanitari elevati', 'Porta prescrizioni mediche'],
  },
  {
    country: 'Argentina',
    flag: '🇦🇷',
    vaccines: [
      { name: 'Febbre Gialla', required: false, notes: 'Per zone di confine con Brasile' },
      { name: 'Epatite A', required: false, notes: 'Per precauzione' },
      { name: 'Epatite B', required: false, notes: 'Per soggiorni prolungati' },
    ],
    medicines: ['Protezione solare SPF50+', 'Medicine per altitudine (nord-ovest)', 'Farmaci personali', 'Repellente insetti'],
    emergencyNumber: '107',
    tips: ['Acqua potabile nelle grandi città', 'Attenzione al mal di montagna nel nord', 'Sistema sanitario pubblico gratuito per emergenze'],
  },
  {
    country: 'Colombia',
    flag: '🇨🇴',
    vaccines: [
      { name: 'Febbre Gialla', required: true, notes: 'Per zone sotto 2300m' },
      { name: 'Epatite A', required: true, notes: 'Consigliato per tutti' },
      { name: 'Epatite B', required: false, notes: 'Per soggiorni prolungati' },
      { name: 'Febbre Tifoide', required: false, notes: 'Per zone rurali' },
      { name: 'Rabbia', required: false, notes: 'Per zone rurali' },
    ],
    medicines: ['Antimalarici (zone tropicali)', 'Repellente DEET 30%+', 'Antidiarroici', 'Protezione solare SPF50+', 'Medicine per altitudine (Bogotà)'],
    emergencyNumber: '123',
    tips: ['Vaccino febbre gialla per zone tropicali', 'Attenzione al mal di montagna a Bogotà (2600m)', 'Repellente zanzare nelle zone calde'],
  },
  {
    country: 'Perù',
    flag: '🇵🇪',
    vaccines: [
      { name: 'Febbre Gialla', required: true, notes: 'Per zone amazzoniche' },
      { name: 'Epatite A', required: true, notes: 'Consigliato per tutti' },
      { name: 'Epatite B', required: false, notes: 'Per soggiorni prolungati' },
      { name: 'Febbre Tifoide', required: false, notes: 'Per zone rurali' },
      { name: 'Rabbia', required: false, notes: 'Per zone rurali' },
    ],
    medicines: ['Medicine per altitudine (Diamox)', 'Antimalarici (Amazzonia)', 'Repellente DEET 30%+', 'Antidiarroici', 'Foglie di coca per altitudine'],
    emergencyNumber: '116',
    tips: ['Mal di montagna: acclimatarsi gradualmente', 'Solo acqua in bottiglia', 'Profilassi antimalarica per Amazzonia'],
  },
  {
    country: 'Cuba',
    flag: '🇨🇺',
    vaccines: [
      { name: 'Epatite A', required: true, notes: 'Consigliato per tutti' },
      { name: 'Epatite B', required: false, notes: 'Per soggiorni prolungati' },
      { name: 'Febbre Tifoide', required: false, notes: 'Per zone rurali' },
    ],
    medicines: ['Antidiarroici', 'Repellente per zanzare', 'Protezione solare SPF50+', 'Farmaci personali (difficili da trovare localmente)', 'Kit pronto soccorso completo'],
    emergencyNumber: '104',
    tips: ['Porta tutti i farmaci necessari (carenza locale)', 'Assicurazione sanitaria obbligatoria', 'Sistema sanitario buono ma carenza di medicinali'],
  },
  {
    country: 'Emirati Arabi',
    flag: '🇦🇪',
    vaccines: [
      { name: 'Nessun vaccino obbligatorio', required: false, notes: 'Verifica copertura vaccinale standard' },
    ],
    medicines: ['Protezione solare SPF50+', 'Reidratazione orale', 'Farmaci personali con prescrizione'],
    emergencyNumber: '998',
    tips: ['Sistema sanitario eccellente', 'Attenzione al caldo estremo estivo', 'Porta farmaci con prescrizione (controlli severi)'],
  },
  {
    country: 'Arabia Saudita',
    flag: '🇸🇦',
    vaccines: [
      { name: 'Meningite', required: true, notes: 'Obbligatorio per pellegrinaggio (Hajj/Umrah)' },
      { name: 'Polio', required: false, notes: 'Richiamo consigliato' },
      { name: 'Febbre Gialla', required: false, notes: 'Se arrivi da paese endemico' },
    ],
    medicines: ['Protezione solare SPF50+', 'Reidratazione orale', 'Farmaci personali con prescrizione'],
    emergencyNumber: '997',
    tips: ['Vaccino meningite obbligatorio per Hajj', 'Attenzione al caldo estremo', 'Farmaci con prescrizione obbligatoria'],
  },
  {
    country: 'Israele',
    flag: '🇮🇱',
    vaccines: [
      { name: 'Nessun vaccino obbligatorio', required: false, notes: 'Verifica copertura vaccinale standard' },
    ],
    medicines: ['Protezione solare SPF50+', 'Reidratazione orale', 'Farmaci personali'],
    emergencyNumber: '101',
    tips: ['Sistema sanitario eccellente', 'Attenzione al caldo nel deserto del Negev', 'Bevi molta acqua'],
  },
  {
    country: 'Nuova Zelanda',
    flag: '🇳🇿',
    vaccines: [
      { name: 'Nessun vaccino obbligatorio', required: false, notes: 'Verifica copertura vaccinale standard' },
    ],
    medicines: ['Protezione solare SPF50+', 'Repellente sandfly', 'Farmaci personali'],
    emergencyNumber: '111',
    tips: ['Protezione solare indispensabile (buco ozono)', 'Attenzione ai sandfly', 'ACC copre incidenti per turisti'],
  },
  {
    country: 'Malesia',
    flag: '🇲🇾',
    vaccines: [
      { name: 'Epatite A', required: true, notes: 'Consigliato per tutti' },
      { name: 'Epatite B', required: false, notes: 'Per soggiorni prolungati' },
      { name: 'Febbre Tifoide', required: false, notes: 'Per zone rurali' },
      { name: 'Rabbia', required: false, notes: 'Per zone rurali del Borneo' },
    ],
    medicines: ['Repellente DEET 30%+', 'Antidiarroici', 'Protezione solare SPF50+', 'Antimalarici (Borneo rurale)', 'Reidratazione orale'],
    emergencyNumber: '999',
    tips: ['Repellente zanzare essenziale (Dengue)', 'Acqua del rubinetto generalmente sicura a KL', 'Sistema sanitario buono nelle città'],
  },
  {
    country: 'Singapore',
    flag: '🇸🇬',
    vaccines: [
      { name: 'Nessun vaccino obbligatorio', required: false, notes: 'Verifica copertura vaccinale standard' },
    ],
    medicines: ['Protezione solare', 'Repellente per zanzare', 'Farmaci personali'],
    emergencyNumber: '995',
    tips: ['Paese molto sicuro sanitariamente', 'Sistema sanitario tra i migliori al mondo', 'Repellente zanzare consigliato (Dengue presente)'],
  },
  {
    country: 'Islanda',
    flag: '🇮🇸',
    vaccines: [
      { name: 'Nessun vaccino obbligatorio', required: false, notes: 'Tessera sanitaria europea valida' },
    ],
    medicines: ['Protezione solare (riflesso neve/ghiaccio)', 'Crema idratante (aria secca)', 'Farmaci personali'],
    emergencyNumber: '112',
    tips: ['Tessera sanitaria europea (TEAM) valida', 'Attenzione al freddo estremo', 'Acqua del rubinetto tra le più pure al mondo'],
  },
  {
    country: 'Russia',
    flag: '🇷🇺',
    vaccines: [
      { name: 'Encefalite da zecche (TBE)', required: false, notes: 'Per zone rurali e forestali' },
      { name: 'Epatite A', required: false, notes: 'Per precauzione' },
      { name: 'Epatite B', required: false, notes: 'Per soggiorni prolungati' },
    ],
    medicines: ['Repellente antizecche', 'Farmaci personali', 'Antidiarroici', 'Kit pronto soccorso'],
    emergencyNumber: '103',
    tips: ['Assicurazione sanitaria obbligatoria per visto', 'Attenzione alle zecche in Siberia', 'Porta farmaci personali (difficili da trovare)'],
  },
  {
    country: 'Svizzera',
    flag: '🇨🇭',
    vaccines: [
      { name: 'Encefalite da zecche (TBE)', required: false, notes: 'Per zone rurali e forestali' },
    ],
    medicines: ['Repellente antizecche', 'Farmaci personali', 'Protezione solare montagna'],
    emergencyNumber: '144',
    tips: ['Tessera sanitaria europea NON valida (non UE)', 'Assicurazione sanitaria necessaria', 'Costi sanitari molto elevati'],
  },
  {
    country: 'Croazia',
    flag: '🇭🇷',
    vaccines: [
      { name: 'Encefalite da zecche (TBE)', required: false, notes: 'Per zone rurali e forestali' },
    ],
    medicines: ['Protezione solare SPF50+', 'Repellente antizecche', 'Farmaci personali'],
    emergencyNumber: '194',
    tips: ['Tessera sanitaria europea (TEAM) valida', 'Attenzione ai ricci di mare in spiaggia', 'Protezione solare indispensabile sulla costa'],
  },
  {
    country: 'Polonia',
    flag: '🇵🇱',
    vaccines: [
      { name: 'Encefalite da zecche (TBE)', required: false, notes: 'Per zone rurali e forestali' },
    ],
    medicines: ['Repellente antizecche', 'Farmaci personali', 'Cerotti e disinfettante'],
    emergencyNumber: '999',
    tips: ['Tessera sanitaria europea (TEAM) valida', 'Sistema sanitario in miglioramento', 'Attenzione alle zecche in zone boschive'],
  },
];
