import { QuizQuestion, ProfileResult } from '@/types';

export const quizQuestions: QuizQuestion[] = [
  {
    id: 1,
    question: 'Quale esperienza preferisci?',
    options: [
      { id: '1a', text: 'Vacanza al mare', icon: 'Palmtree', profiles: ['beach_lover'] },
      { id: '1b', text: 'Avventura in montagna', icon: 'Mountain', profiles: ['mountain_explorer'] },
      { id: '1c', text: 'Esplorazione urbana', icon: 'Building2', profiles: ['city_wanderer'] },
      { id: '1d', text: 'Viaggio avventuroso', icon: 'Compass', profiles: ['adventure_seeker'] },
    ],
  },
  {
    id: 2,
    question: 'Che tipo di alloggio cerchi?',
    options: [
      { id: '2a', text: 'Hotel di lusso', icon: 'Hotel', profiles: ['luxury_traveler'] },
      { id: '2b', text: 'Campeggio', icon: 'Tent', profiles: ['adventure_seeker', 'mountain_explorer'] },
      { id: '2c', text: 'Appartamento privato', icon: 'Home', profiles: ['city_wanderer', 'beach_lover'] },
      { id: '2d', text: 'Ostello', icon: 'Bed', profiles: ['budget_backpacker'] },
    ],
  },
  {
    id: 3,
    question: 'Come ti piace viaggiare?',
    options: [
      { id: '3a', text: 'In aereo', icon: 'Plane', profiles: ['luxury_traveler', 'adventure_seeker'] },
      { id: '3b', text: 'In treno', icon: 'TrainFront', profiles: ['city_wanderer'] },
      { id: '3c', text: 'In auto', icon: 'Car', profiles: ['mountain_explorer', 'beach_lover'] },
      { id: '3d', text: 'In autobus', icon: 'Bus', profiles: ['budget_backpacker'] },
    ],
  },
  {
    id: 4,
    question: 'Con chi viaggi di solito?',
    options: [
      { id: '4a', text: 'Da solo', icon: 'User', profiles: ['adventure_seeker', 'budget_backpacker'] },
      { id: '4b', text: 'In coppia', icon: 'Heart', profiles: ['beach_lover', 'luxury_traveler'] },
      { id: '4c', text: 'In famiglia', icon: 'Users', profiles: ['beach_lover', 'city_wanderer'] },
      { id: '4d', text: 'Con amici', icon: 'UsersRound', profiles: ['budget_backpacker', 'adventure_seeker'] },
    ],
  },
  {
    id: 5,
    question: 'Qual è il tuo budget di viaggio?',
    options: [
      { id: '5a', text: 'Economico', icon: 'Coins', profiles: ['budget_backpacker'] },
      { id: '5b', text: 'Medio', icon: 'Banknote', profiles: ['city_wanderer', 'mountain_explorer'] },
      { id: '5c', text: 'Alto', icon: 'Gem', profiles: ['beach_lover', 'adventure_seeker'] },
      { id: '5d', text: 'Lusso', icon: 'Crown', profiles: ['luxury_traveler'] },
    ],
  },
  {
    id: 6,
    question: 'Cosa preferisci fare in vacanza?',
    options: [
      { id: '6a', text: 'Relax totale', icon: 'Armchair', profiles: ['beach_lover', 'luxury_traveler'] },
      { id: '6b', text: 'Sport e attività', icon: 'Bike', profiles: ['mountain_explorer', 'adventure_seeker'] },
      { id: '6c', text: 'Cultura e musei', icon: 'Landmark', profiles: ['city_wanderer'] },
      { id: '6d', text: 'Vita notturna', icon: 'Moon', profiles: ['budget_backpacker', 'city_wanderer'] },
    ],
  },
  {
    id: 7,
    question: 'Durata ideale viaggio?',
    options: [
      { id: '7a', text: 'Weekend (2-3 giorni)', icon: 'CalendarDays', profiles: ['city_wanderer'] },
      { id: '7b', text: 'Settimana (5-7 giorni)', icon: 'CalendarDays', profiles: ['beach_lover', 'mountain_explorer'] },
      { id: '7c', text: 'Due settimane', icon: 'CalendarDays', profiles: ['adventure_seeker', 'luxury_traveler'] },
      { id: '7d', text: 'Un mese o più', icon: 'CalendarDays', profiles: ['budget_backpacker', 'adventure_seeker'] },
    ],
  },
  {
    id: 8,
    question: 'Clima preferito?',
    options: [
      { id: '8a', text: 'Caldo e sole', icon: 'Sun', profiles: ['beach_lover', 'luxury_traveler'] },
      { id: '8b', text: 'Fresco e ventilato', icon: 'Wind', profiles: ['mountain_explorer', 'city_wanderer'] },
      { id: '8c', text: 'Freddo e neve', icon: 'Snowflake', profiles: ['mountain_explorer', 'adventure_seeker'] },
      { id: '8d', text: 'Vario', icon: 'CloudSun', profiles: ['adventure_seeker', 'budget_backpacker'] },
    ],
  },
];

export const profileResults: Record<string, ProfileResult> = {
  beach_lover: {
    type: 'beach_lover',
    title: 'Amante del Mare',
    icon: 'Palmtree',
    image: 'https://r2-pub.rork.com/generated-images/dbe4c853-ff0c-4b63-8b3f-de127e73495e.png',
    description:
      'Sei un viaggiatore che cerca relax e bellezze naturali. Le spiagge paradisiache e il suono delle onde sono la tua felicità. Ami goderti tramonti spettacolari e la brezza marina, sempre alla ricerca della prossima costa da esplorare.',
    color: '#4DD0E1',
    motto: '"La vita è meglio in infradito"',
    strengths: ['Sai trovare la spiaggia perfetta ovunque', 'Maestro nell\'arte del relax totale', 'Occhio infallibile per i tramonti più belli', 'Capacità innata di rallentare il ritmo'],
    idealCompanion: 'Il tuo compagno ideale è qualcuno che sa apprezzare il silenzio delle onde e non ha fretta di andare da nessuna parte. Insieme, ogni granello di sabbia diventa un ricordo.',
    mustHaveItems: ['Crema solare SPF 50', 'Libro da leggere sotto l\'ombrellone', 'Maschera da snorkeling', 'Amaca portatile', 'Fotocamera subacquea'],
    spiritAnimal: '🐬 Delfino — Giocoso, sociale e perfettamente a suo agio tra le onde',
    travelStyle: 'Slow travel con lunghe soste in paradisi tropicali. Preferisci pochi posti ma vissuti intensamente, svegliandoti col rumore del mare ogni mattina.',
    favoriteFood: 'Pesce fresco alla griglia con lime, ceviche, cocktail di frutta tropicale e tutto ciò che sa di sale e sole',
    soundtrack: '🎵 Bob Marley, Jack Johnson, onde del mare in sottofondo',
    stats: [
      { label: 'Relax', value: 95 },
      { label: 'Avventura', value: 40 },
      { label: 'Cultura', value: 35 },
      { label: 'Socialità', value: 70 },
      { label: 'Spontaneità', value: 60 },
    ],
  },
  mountain_explorer: {
    type: 'mountain_explorer',
    title: 'Esploratore di Montagna',
    icon: 'Mountain',
    image: 'https://r2-pub.rork.com/generated-images/ec5b678b-53c7-4d6a-a941-39cfa272cbd5.png',
    description:
      'Le vette innevate e i sentieri nascosti sono il tuo habitat naturale. Ami la sfida fisica e la ricompensa di panorami mozzafiato. Ogni escursione è un\'avventura che ti avvicina alla natura e a te stesso.',
    color: '#7B68EE',
    motto: '"Non è la montagna che conquistiamo, ma noi stessi"',
    strengths: ['Resistenza fisica e mentale eccezionale', 'Senso dell\'orientamento innato', 'Capacità di adattarsi a condizioni estreme', 'Pazienza nel raggiungere obiettivi ambiziosi'],
    idealCompanion: 'Cerchi qualcuno che non si lamenta dopo il terzo chilometro in salita e che sa condividere il silenzio maestoso di una vetta raggiunta insieme.',
    mustHaveItems: ['Scarponi da trekking rodati', 'Bastoncini telescopici', 'Thermos con tè caldo', 'GPS da polso', 'Giacca impermeabile ultraleggera'],
    spiritAnimal: '🦅 Aquila — Visione ampia, spirito libero e padronanza delle altitudini',
    travelStyle: 'Trekking multi-giorno con rifugi e bivacchi. Ogni viaggio è una sfida personale, pianificata nei dettagli ma aperta alle sorprese che solo la montagna sa regalare.',
    favoriteFood: 'Polenta con formaggio fuso, zuppe calde di legumi, speck e pane di segale davanti al camino del rifugio',
    soundtrack: '🎵 Ludovico Einaudi, suoni della natura, vento tra le cime',
    stats: [
      { label: 'Relax', value: 30 },
      { label: 'Avventura', value: 90 },
      { label: 'Cultura', value: 45 },
      { label: 'Resistenza', value: 95 },
      { label: 'Spontaneità', value: 50 },
    ],
  },
  city_wanderer: {
    type: 'city_wanderer',
    title: 'Vagabondo Urbano',
    icon: 'Building2',
    image: 'https://r2-pub.rork.com/generated-images/f53f4d77-3b68-4874-868b-5e3d9dedd86f.png',
    description:
      'Le città sono il tuo parco giochi. Musei, architettura, street food e vita notturna ti attraggono irresistibilmente. Ami perderti nei vicoli di una nuova metropoli e scoprire gemme nascoste ad ogni angolo.',
    color: '#FF8A80',
    motto: '"Ogni città ha un\'anima, basta saperla ascoltare"',
    strengths: ['Fiuto per i quartieri più autentici', 'Capacità di orientarsi in qualsiasi metropoli', 'Talento nel trovare i locali nascosti', 'Adattamento fulmineo ai ritmi urbani'],
    idealCompanion: 'Qualcuno che ama camminare per ore senza meta precisa, fermarsi in caffetterie sconosciute e discutere di arte davanti a un murale di strada.',
    mustHaveItems: ['Scarpe comode da camminata urbana', 'City map offline', 'Taccuino per schizzi e appunti', 'Pass musei e trasporti', 'Macchina fotografica street'],
    spiritAnimal: '🦊 Volpe — Curiosa, astuta e sempre un passo avanti nella scoperta',
    travelStyle: 'City hopping intenso con 20.000 passi al giorno. Ti svegli presto per i mercati, pranzi con lo street food e chiudi la serata nei jazz bar nascosti.',
    favoriteFood: 'Street food locale di ogni tipo: tacos, dim sum, falafel, pizza al taglio — il cibo di strada è la vera guida della città',
    soundtrack: '🎵 Jazz, indie rock, il brusio dei caffè e il clacson dei taxi',
    stats: [
      { label: 'Relax', value: 25 },
      { label: 'Avventura', value: 65 },
      { label: 'Cultura', value: 95 },
      { label: 'Socialità', value: 85 },
      { label: 'Spontaneità', value: 80 },
    ],
  },
  adventure_seeker: {
    type: 'adventure_seeker',
    title: 'Cercatore di Avventure',
    icon: 'Compass',
    image: 'https://r2-pub.rork.com/generated-images/12110f51-dd79-440e-b04e-e5c941a6bb61.png',
    description:
      'Sei un viaggiatore che ama l\'ignoto e le sfide. La tua curiosità ti spinge verso luoghi remoti e culture autentiche, sempre alla ricerca di esperienze uniche che ti facciano sentire vivo.',
    color: '#4DD0E1',
    motto: '"La vita inizia dove finisce la zona di comfort"',
    strengths: ['Coraggio di esplorare l\'ignoto', 'Adattabilità a qualsiasi situazione', 'Capacità di connettere con culture diverse', 'Spirito indomabile e resiliente'],
    idealCompanion: 'Un\'anima avventurosa che non ha paura di cambiare programma all\'ultimo momento e che sa trasformare ogni imprevisto in una storia da raccontare.',
    mustHaveItems: ['Coltellino multiuso', 'Power bank solare', 'Amaca ultraleggera', 'Kit primo soccorso', 'GoPro per immortalare le imprese'],
    spiritAnimal: '🐆 Leopardo — Veloce, imprevedibile e sempre pronto a lanciarsi nell\'avventura',
    travelStyle: 'Off the beaten path. Niente percorsi turistici: preferisci giungle inesplorate, deserti remoti e villaggi dove nessun turista è mai arrivato prima.',
    favoriteFood: 'Tutto ciò che è locale e autentico: insetti fritti in Thailandia, tajine nel deserto, carne di lama sulle Ande — più è insolito, meglio è',
    soundtrack: '🎵 Rulli di tamburi tribali, Rodrigo y Gabriela, suoni della giungla',
    stats: [
      { label: 'Relax', value: 15 },
      { label: 'Avventura', value: 99 },
      { label: 'Cultura', value: 70 },
      { label: 'Resistenza', value: 85 },
      { label: 'Spontaneità', value: 95 },
    ],
  },
  luxury_traveler: {
    type: 'luxury_traveler',
    title: 'Viaggiatore di Lusso',
    icon: 'Crown',
    image: 'https://r2-pub.rork.com/generated-images/f5e7a7e6-f1fd-45e5-b645-4eeeae42d913.png',
    description:
      'Per te viaggiare è sinonimo di comfort e raffinatezza. Hotel a 5 stelle, ristoranti stellati e esperienze esclusive sono il tuo modo di esplorare il mondo con eleganza e stile.',
    color: '#7B68EE',
    motto: '"Il vero lusso è il tempo speso con stile"',
    strengths: ['Occhio infallibile per la qualità', 'Capacità di trasformare ogni viaggio in un\'esperienza indimenticabile', 'Gusto raffinato per i dettagli', 'Networking internazionale naturale'],
    idealCompanion: 'Qualcuno che apprezza le cose belle della vita senza ostentarle, che sa godersi un calice di champagne al tramonto e una spa di lusso con la stessa eleganza.',
    mustHaveItems: ['Valigia Rimowa', 'Abbonamento priority lounge', 'Guida Michelin aggiornata', 'Skincare da viaggio premium', 'Cuffie noise-cancelling'],
    spiritAnimal: '🦢 Cigno — Elegante, raffinato e maestoso in ogni movimento',
    travelStyle: 'First class e suite presidenziali. Ogni dettaglio è curato: dal transfer privato alla degustazione di vini in cantina, passando per il massaggio ayurvedico al tramonto.',
    favoriteFood: 'Cucina stellata Michelin, ostriche fresche, tartufo bianco d\'Alba, sushi omakase e vini d\'annata pregiati',
    soundtrack: '🎵 Chopin, Norah Jones, lounge music in terrazza panoramica',
    stats: [
      { label: 'Relax', value: 85 },
      { label: 'Avventura', value: 30 },
      { label: 'Cultura', value: 75 },
      { label: 'Comfort', value: 99 },
      { label: 'Spontaneità', value: 35 },
    ],
  },
  budget_backpacker: {
    type: 'budget_backpacker',
    title: 'Zaino in Spalla',
    icon: 'Backpack',
    image: 'https://r2-pub.rork.com/generated-images/5157a437-e938-436b-ab58-bc635cef1cfa.png',
    description:
      'La libertà è il tuo lusso più grande. Con uno zaino e tanta curiosità, esplori il mondo senza limiti. Ostelli, street food e incontri con altri viaggiatori rendono ogni viaggio indimenticabile.',
    color: '#FF8A80',
    motto: '"Non ho bisogno di molto per essere felice, solo di un biglietto di sola andata"',
    strengths: ['Maestro nel risparmiare senza rinunciare a nulla', 'Capacità di fare amicizia con chiunque', 'Flessibilità totale nei piani', 'Creatività nell\'organizzare con poco'],
    idealCompanion: 'Un altro spirito libero che non si preoccupa di dormire in un letto a castello e che sa che le migliori avventure nascono dalle conversazioni negli ostelli.',
    mustHaveItems: ['Zaino 40L ultraleggero', 'Sacco a pelo compatto', 'App per voli low-cost', 'Lucchetto per armadietti ostello', 'Diario di viaggio'],
    spiritAnimal: '🐒 Scimmia — Giocosa, sociale, adattabile e sempre in movimento',
    travelStyle: 'Slow travel low-cost. Autobus notturni, couchsurfing, volontariato in cambio di alloggio. Il budget è stretto ma le esperienze sono immense e autentiche.',
    favoriteFood: 'Street food economico e delizioso: pad thai a 1€, arepas sul marciapiede, panini dal forno locale — il gusto non dipende dal prezzo',
    soundtrack: '🎵 Chitarra acustica in spiaggia, reggae, canzoni cantate attorno al fuoco',
    stats: [
      { label: 'Relax', value: 40 },
      { label: 'Avventura', value: 80 },
      { label: 'Cultura', value: 60 },
      { label: 'Socialità', value: 99 },
      { label: 'Spontaneità', value: 90 },
    ],
  },
};
